exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--strict"]
        exclude: "."
        additional_dependencies:
          - django-stubs
          - celery
          - django-environ
          - django-extensions
          - django-crispy-forms
          - crispy-bootstrap5
          - django-allauth
          - django-celery-beat
          - djangorestframework
          - djangorestframework-datatables
          - django-debug-toolbar
          - psycopg2-binary
          - python-slugify
          - xmltodict
          - PyGithub
          - boto3
          - scrapy
          - types-requests

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
      - id: bandit
        args: ['-r', '--configfile=bandit-config.yml']

  - repo: https://github.com/zricethezav/gitleaks
    rev: 'v8.0.4'
    hooks:
      - id: gitleaks
        args: ['--config=gitleaks-config.toml']

  - repo: local
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        entry: bash -c 'if [ -z "$CI" ]; then docker run --rm -i hadolint/hadolint hadolint -- -; fi'
        language: system
        types: [dockerfile]
        pass_filenames: false

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
