python manage.py loaddata scraper/scraped_urls/algorithm_theoretical_basis_documents/urls.json
python manage.py loaddata scraper/scraped_urls/astrogeology_analysis_ready_data/urls.json
python manage.py loaddata scraper/scraped_urls/astromaterials_acquisition_and_curation_office/urls.json
python manage.py loaddata scraper/scraped_urls/earth_observer_publications/urls.json
python manage.py loaddata scraper/scraped_urls/earth_observing_dashboard/urls.json
python manage.py loaddata scraper/scraped_urls/emac_exoplanet_modeling_and_analysis_center/urls.json
python manage.py loaddata scraper/scraped_urls/eos_mission_page/urls.json
python manage.py loaddata scraper/scraped_urls/exoplanet_opacities_database/urls.json
python manage.py loaddata scraper/scraped_urls/f_prime/urls.json
python manage.py loaddata scraper/scraped_urls/fire_information_for_resource_management_system_firms/urls.json
python manage.py loaddata scraper/scraped_urls/gcn_circulars/urls.json
python manage.py loaddata scraper/scraped_urls/gcn_missions_instruments_and_facilities/urls.json
python manage.py loaddata scraper/scraped_urls/GENELAB_Publications_Website/urls.json
python manage.py loaddata scraper/scraped_urls/general_coordinates_network_gcn/urls.json
python manage.py loaddata scraper/scraped_urls/giss_datasets_and_derived_materials/urls.json
python manage.py loaddata scraper/scraped_urls/giss_publication_list/urls.json
python manage.py loaddata scraper/scraped_urls/giss_software_tools/urls.json
python manage.py loaddata scraper/scraped_urls/goddard_institute_for_space_studies/urls.json
python manage.py loaddata scraper/scraped_urls/heliophysics_events_knowledgebase/urls.json
python manage.py loaddata scraper/scraped_urls/igwn_public_alerts_user_guide/urls.json
python manage.py loaddata scraper/scraped_urls/interactive_multiinstrument_database_of_solar_flares/urls.json
python manage.py loaddata scraper/scraped_urls/mars_exploration_program/urls.json
python manage.py loaddata scraper/scraped_urls/mars_target_encyclopedia/urls.json
python manage.py loaddata scraper/scraped_urls/my_nasa_data/urls.json
python manage.py loaddata scraper/scraped_urls/nasa_carbon_monitoring_system/urls.json
python manage.py loaddata scraper/scraped_urls/nasa_global_climate_change/urls.json
python manage.py loaddata scraper/scraped_urls/nasa_power/urls.json
python manage.py loaddata scraper/scraped_urls/nasa_science_earths_moon/urls.json
python manage.py loaddata scraper/scraped_urls/nasa_science_missions_earth/urls.json
python manage.py loaddata scraper/scraped_urls/nasa_sea_level_change/urls.json
python manage.py loaddata scraper/scraped_urls/nasa_wavelength/urls.json
python manage.py loaddata scraper/scraped_urls/our_changing_planet_the_view_from_space_images/urls.json
python manage.py loaddata scraper/scraped_urls/PDS_Astropedia_Lunar_and_Planetary_Cartographic_Catalog_Website/urls.json
python manage.py loaddata scraper/scraped_urls/PDS_Cassini_Resource_Page_Website/urls.json
python manage.py loaddata scraper/scraped_urls/PDS_NASA_Science_Solar_System_Exploration_Website/urls.json
python manage.py loaddata scraper/scraped_urls/pds_near_earth_asteroid_rendezvous_near_data_archive_website/urls.json
python manage.py loaddata scraper/scraped_urls/PDS_Recently_Archived_Volumes_Website/urls.json
python manage.py loaddata scraper/scraped_urls/PDS_Small_Bodies_Data_Ferret_Website/urls.json
python manage.py loaddata scraper/scraped_urls/pds4_documents/urls.json
python manage.py loaddata scraper/scraped_urls/solar_system_exploration_research_virtual_institute_sservi/urls.json
