python manage.py loaddata scraper/scraped_urls/mars_exploration_program/urls.json # 90177
python manage.py loaddata scraper/scraped_urls/solar_system_exploration_research_virtual_institute_sservi/urls.json # 9
python manage.py loaddata scraper/scraped_urls/nasa_carbon_monitoring_system/urls.json # 345
python manage.py loaddata scraper/scraped_urls/interactive_multiinstrument_database_of_solar_flares/urls.json # 9
python manage.py loaddata scraper/scraped_urls/our_changing_planet_the_view_from_space_images/urls.json # 125
python manage.py loaddata scraper/scraped_urls/fire_information_for_resource_management_system_firms/urls.json # 86
python manage.py loaddata scraper/scraped_urls/astropedia_lunar_and_planetary_cartographic_catalog/urls.json # 98080
python manage.py loaddata scraper/scraped_urls/nasa_science_missions_earth/urls.json # 18558
python manage.py loaddata scraper/scraped_urls/pds_near_earth_asteroid_rendezvous_near_data_archive_website/urls.json # 1319
python manage.py loaddata scraper/scraped_urls/nasa_science_earths_moon/urls.json # 608
python manage.py loaddata scraper/scraped_urls/astromaterials_acquisition_and_curation_office/urls.json # 11594
python manage.py loaddata scraper/scraped_urls/f_prime/urls.json # 43168
python manage.py loaddata scraper/scraped_urls/exoplanet_opacities_database/urls.json # 4
python manage.py loaddata scraper/scraped_urls/my_nasa_data/urls.json # 99416
python manage.py loaddata scraper/scraped_urls/earth_science_decadal_surveys/urls.json # 2
python manage.py loaddata scraper/scraped_urls/emac_exoplanet_modeling_and_analysis_center/urls.json # 282
python manage.py loaddata scraper/scraped_urls/eos_mission_page/urls.json # 125
python manage.py loaddata scraper/scraped_urls/algorithm_theoretical_basis_documents/urls.json # 125
python manage.py loaddata scraper/scraped_urls/mars_target_encyclopedia/urls.json # 43377
python manage.py loaddata scraper/scraped_urls/general_coordinates_network_gcn/urls.json # 60653
python manage.py loaddata scraper/scraped_urls/nasa_sea_level_change/urls.json # 629
python manage.py loaddata scraper/scraped_urls/giss_datasets_and_derived_materials/urls.json # 6317
python manage.py loaddata scraper/scraped_urls/earth_observing_dashboard/urls.json # 3
python manage.py loaddata scraper/scraped_urls/nasa_science_solar_system_exploration/urls.json # 89569
python manage.py loaddata scraper/scraped_urls/pds4_documents/urls.json # 137
python manage.py loaddata scraper/scraped_urls/gcn_circulars/urls.json # 61231
python manage.py loaddata scraper/scraped_urls/gcn_missions_instruments_and_facilities/urls.json # 60653
python manage.py loaddata scraper/scraped_urls/pds_cassini_resource_page_website/urls.json # 96260
python manage.py loaddata scraper/scraped_urls/heliophysics_events_knowledgebase/urls.json # 4
python manage.py loaddata scraper/scraped_urls/giss_publication_list/urls.json # 5803
python manage.py loaddata scraper/scraped_urls/giss_software_tools/urls.json # 63
python manage.py loaddata scraper/scraped_urls/goddard_institute_for_space_studies/urls.json # 3076
python manage.py loaddata scraper/scraped_urls/nasa_wavelength/urls.json # 474
python manage.py loaddata scraper/scraped_urls/nasa_power/urls.json # 169
python manage.py loaddata scraper/scraped_urls/igwn_public_alerts_user_guide/urls.json # 39
python manage.py loaddata scraper/scraped_urls/astrogeology_analysis_ready_data/urls.json # 29
python manage.py loaddata scraper/scraped_urls/nasa_global_climate_change/urls.json # 2379
