# Generated by Django 4.2.9 on 2025-02-13 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sde_collections", "0075_alter_collection_reindexing_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_job_id", models.CharField(help_text="Job ID returned by the inference API", max_length=255)),
                ("url_ids", models.JSONField(help_text="List of URL IDs included in this batch")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Queued"),
                            (2, "Pending"),
                            (3, "Completed"),
                            (4, "Failed"),
                            (5, "Cancelled"),
                            (6, "Not Found"),
                            (7, "Unknown"),
                        ],
                        default=1,
                    ),
                ),
                ("results", models.JSONField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InferenceJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Queued"), (2, "Pending"), (3, "Completed"), (4, "Failed"), (5, "Cancelled")],
                        default=1,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_identifier", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "classification_type",
                    models.IntegerField(
                        choices=[(1, "TDAMM Classification"), (2, "Division Classification")],
                        help_text="Type of classification this model performs",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this is the current active version for its classification type"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("classification_type", "is_active"),
                name="unique_active_version",
            ),
        ),
        migrations.AddField(
            model_name="inferencejob",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inference_jobs",
                to="sde_collections.collection",
            ),
        ),
        migrations.AddField(
            model_name="inferencejob",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="inference_jobs", to="inference.modelversion"
            ),
        ),
        migrations.AddField(
            model_name="externaljob",
            name="inference_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="external_jobs", to="inference.inferencejob"
            ),
        ),
        migrations.AddConstraint(
            model_name="inferencejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", [1, 2])),
                fields=("collection", "model_version"),
                name="unique_active_job",
            ),
        ),
    ]
