# Generated by Django 4.2.9 on 2025-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaljob",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externaljob",
            name="results",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
