# Generated by Django 4.2.6 on 2023-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcurationrequest",
            name="additional_info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
