# Generated by Django 4.2.6 on 2024-01-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_alter_contentcurationrequest_additional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="source",
            field=models.CharField(blank=True, default="SDE", max_length=50),
        ),
    ]
