# Generated by Django 4.2.9 on 2024-02-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_feedback_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcurationrequest",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
