# Generated by Django 4.2.9 on 2025-01-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_contentcurationrequest_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackFormDropdown",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("display_order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Dropdowm Option",
                "verbose_name_plural": "Dropdown Options",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="dropdown_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback",
                to="feedback.feedbackformdropdown",
            ),
        ),
    ]
