# Generated by Django 4.2.9 on 2024-09-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_contentcurationrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="category",
            field=models.TextField(blank=True, default=""),
        ),
    ]
