# Generated by Django 4.2.6 on 2023-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=400)),
                ("comment", models.TextField()),
            ],
            options={
                "verbose_name": "Contact-Us Response",
                "verbose_name_plural": "Contact-Us Responses",
            },
        ),
        migrations.CreateModel(
            name="ContentCurationRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("scientific_focus", models.CharField(max_length=200)),
                ("data_type", models.CharField(max_length=100)),
                ("data_link", models.CharField(max_length=1000)),
                ("additional_info", models.TextField()),
            ],
            options={
                "verbose_name": "Content Curation Request",
                "verbose_name_plural": "Content Curation Requests",
            },
        ),
    ]
