# Generated by Django 4.2.6 on 2023-12-05 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_contactformmodel_contentcurationrequestmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactFormModel",
        ),
        migrations.DeleteModel(
            name="ContentCurationRequestModel",
        ),
    ]
