"""
the ej_dump is generated by running create_ej_dump.py and is scp'd to the COSMOS server
this script is then run via the dm shell on the COSMOS server to populate the database
"""

import json

from environmental_justice.models import EnvironmentalJusticeRow

from .cmr_processing import CmrDataset


def process_ej_dump(file_path: str) -> None:
    """Process EJ dump file and create database entries."""

    destination_server = EnvironmentalJusticeRow.DestinationServerChoices.DEV

    # Clear existing data
    EnvironmentalJusticeRow.objects.filter(destination_server=destination_server).delete()

    # Load the data
    ej_dump = json.load(open(file_path))

    # Process each dataset into the database
    for dataset in ej_dump:
        processed_dataset = CmrDataset(dataset)
        ej_row = EnvironmentalJusticeRow(
            destination_server=destination_server,
            sde_link=processed_dataset.sde_link,
            dataset=processed_dataset.dataset_name,
            description=processed_dataset.description,
            limitations=processed_dataset.limitations,
            format=processed_dataset.format,
            temporal_extent=processed_dataset.temporal_extent,
            intended_use=processed_dataset.intended_use,
            source_link=processed_dataset.source_link,
            indicators=dataset["indicators"],
            strengths=processed_dataset.strengths,
            weaknesses=processed_dataset.weaknesses,
            latency=processed_dataset.latency,
            geographic_coverage=processed_dataset.geographic_coverage,
            data_visualization=processed_dataset.data_visualization,
            temporal_resolution=processed_dataset.temporal_resolution,
            spatial_resolution=processed_dataset.spatial_resolution,
            projects=processed_dataset.projects,
        )
        ej_row.save()


if __name__ == "__main__":
    process_ej_dump("backups/ej_dump_20241017_133151.json")
