# Generated by Django 5.0.1 on 2024-02-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environmental_justice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentaljusticerow",
            name="sde_links",
            field=models.CharField(default="[]", verbose_name="SDE Links"),
            preserve_default=False,
        ),
    ]
