# Generated by Django 5.0.1 on 2024-04-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "environmental_justice",
            "0003_remove_environmentaljusticerow_sde_links_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="data_visualization",
            field=models.CharField(
                blank=True, default="", verbose_name="Data Visualization"
            ),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="dataset",
            field=models.CharField(blank=True, default="", verbose_name="Dataset"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="description",
            field=models.CharField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="description_simplified",
            field=models.CharField(
                blank=True, default="", verbose_name="Description Simplified"
            ),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="format",
            field=models.CharField(blank=True, default="", verbose_name="Format"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="geographic_coverage",
            field=models.CharField(
                blank=True, default="", verbose_name="Geographic Coverage"
            ),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="indicators",
            field=models.CharField(blank=True, default="", verbose_name="Indicators"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="intended_use",
            field=models.CharField(blank=True, default="", verbose_name="Intended Use"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="latency",
            field=models.CharField(blank=True, default="", verbose_name="Latency"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="limitations",
            field=models.CharField(blank=True, default="", verbose_name="Limitations"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="project",
            field=models.CharField(blank=True, default="", verbose_name="Project"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="source_link",
            field=models.CharField(blank=True, default="", verbose_name="Source Link"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="spatial_resolution",
            field=models.CharField(
                blank=True, default="", verbose_name="Spatial Resolution"
            ),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="strengths",
            field=models.CharField(blank=True, default="", verbose_name="Strengths"),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="temporal_extent",
            field=models.CharField(
                blank=True, default="", verbose_name="Temporal Extent"
            ),
        ),
        migrations.AlterField(
            model_name="environmentaljusticerow",
            name="temporal_resolution",
            field=models.CharField(
                blank=True, default="", verbose_name="Temporal Resolution"
            ),
        ),
    ]
