# Generated by Django 4.2.9 on 2024-11-23 03:18

from django.db import migrations, models


def migrate_destination_server_to_data_source(apps, schema_editor):
    EnvironmentalJusticeRow = apps.get_model("environmental_justice", "EnvironmentalJusticeRow")

    # Migrate prod to spreadsheet
    EnvironmentalJusticeRow.objects.filter(destination_server="prod").update(
        data_source="spreadsheet", destination_server=""
    )

    # Migrate dev to ml_production
    EnvironmentalJusticeRow.objects.filter(destination_server="dev").update(
        data_source="ml_production", destination_server=""
    )

    # Migrate test to ml_testing
    EnvironmentalJusticeRow.objects.filter(destination_server="test").update(
        data_source="ml_testing", destination_server=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("environmental_justice", "0005_environmentaljusticerow_destination_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentaljusticerow",
            name="data_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spreadsheet", "Spreadsheet"),
                    ("ml_production", "ML Production"),
                    ("ml_testing", "ML Testing"),
                ],
                default="",
                max_length=20,
                verbose_name="Data Source",
            ),
        ),
        migrations.RunPython(migrate_destination_server_to_data_source, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="environmentaljusticerow",
            name="destination_server",
        ),
    ]
