server {
	listen       80;
	server_name  localhost;

	# Enable gzip compression
	gzip on;
	gzip_comp_level 6;
	gzip_min_length 1024;
	gzip_proxied any;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript application/x-javascript text/x-js text/html;
	gzip_vary on;

	location /media/ {
		alias /usr/share/nginx/media/;
	}
}
