update @@ScienceMissionDirectorate set treepath='Astrophysics/NExScI/'  where collection='/SMD/nexsci/';
update @@ScienceMissionDirectorate set treepath='Biological and Physical Sciences/GeneLab Publications/'  where collection='/SMD/GENELAB_Publications_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Collision Induced Absorption Model/'  where collection='/SMD/PDS_Collision_Induced_Absorption_Model_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/KOA Contributed Datasets/'  where collection='/SMD/ASTRO_Contributed_Datasets_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/NED User Guides/'  where collection='/SMD/ASTRO_NED_User_Guides_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS Data Dictionary Search/'  where collection='/SMD/PDS_Data_Dictionary_Search/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/DIVINER RDR Query V2.0/'  where collection='/SMD/PDS_DIVINER_RDR_Query_V20_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/NEID Solar Radial Velocity Archive/'  where collection='/SMD/neid_solar_radial_velocity_archive/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/James Webb Space Telescope/'  where collection='/SMD/ASTRO_James_Webb_Space_Telescope_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Astropedia: Lunar and Planetary Cartographic Catalog/'  where collection='/SMD/PDS_Astropedia_Lunar_and_Planetary_Cartographic_Catalog_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/HEASARC Tools/'  where collection='/SMD/ASTRO_HEASARC_Tools_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Velocity Calculator/'  where collection='/SMD/velocity_calculator/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Coordinate Calculator/'  where collection='/SMD/coordinate_calculator/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/HEASARC Browse Batch Interface/'  where collection='/SMD/heasarc_browse_batch_interface/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/NASA Solar System Treks/'  where collection='/SMD/PDS_NASA_Solar_System_Treks_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/NASA Science Solar System Exploration/'  where collection='/SMD/PDS_NASA_Science_Solar_System_Exploration_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Ring-Moon Systems Node Open-Source Software/'  where collection='/SMD/PDS_Toolkits_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Missions Archive Page/'  where collection='/SMD/PDS_Missions_Archive_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS Image Atlas/'  where collection='/SMD/PDS_Image_Atlas_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/IRSA Image Cutouts/'  where collection='/SMD/ASTRO_Image_Cutouts_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Uranus Data Archive/'  where collection='/SMD/PDS_Uranus_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS Cartography and Imaging Node Sciences Node Documentation/'  where collection='/SMD/PDS_PDS_Documentation_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Spitzer Tools/'  where collection='/SMD/ASTRO_Spitzer_Tools_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Planetary Image Locator Tool (PILOT)/'  where collection='/SMD/PDS_Data_Pilot_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Explicit Planetary Isentropic Coordinate (EPIC) Model/'  where collection='/SMD/PDS_EPIC_Model_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mars Orbiter Data/'  where collection='/SMD/PDS_Mars_Orbiter_Data_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/MRO Coordinated Observation/'  where collection='/SMD/PDS_MRO_Coordinated_Observation_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS4 Training Documents/'  where collection='/SMD/PDS_PDS4_Training_Documents_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Solar System Exploration Research Virtual Institute (SSERVI)/'  where collection='/SMD/PDS_Solar_System_Exploration_Research_Virtual_Institute_(SSERVI)_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Planetary Gravity Models/'  where collection='/SMD/PDS_Gravity_Models_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS4 Documents/'  where collection='/SMD/PDS_PDS4_Documents_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/SPICE Self-Training/'  where collection='/SMD/PDS_SPICE_Self-Training_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/CEOS Instruments/'  where collection='/SMD/CEOS_API_I/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Science Suborbital Deployments/'  where collection='/SMD/CASEI_Deployment/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Astrophysics Documents/'  where collection='/SMD/ASTRO_Astrophysics_Documents_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/exo.MAST API/'  where collection='/SMD/ASTRO_exoMAST_API_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Venus Archive Page/'  where collection='/SMD/PDS_Venus_Archive_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Planetary Science Tools/'  where collection='/SMD/PDS_Planetary_Science_Tools_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Planetary Science Data (PDS)/'  where collection='/SMD/PDS_API_Legacy_All/';
update @@ScienceMissionDirectorate set treepath='Biological and Physical Sciences/GeneLab Github Data Processing/'  where collection='/SMD/GENELAB_Github_DataProcessing/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Spectral Classes of Like Stars/'  where collection='/SMD/spectral_classes_of_like_stars/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Planetary Image Galleries/'  where collection='/SMD/planetary_image_galleries/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Data Hosted on LAMBDA/'  where collection='/SMD/ASTRO_Data_Hosted_on_LAMBDA_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/CALDB Documentation/'  where collection='/SMD/ASTRO_Calibration_Documentation_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Small Bodies Node Tools, Utilities, and Interfaces/'  where collection='/SMD/PDS_SBN_Tools_Utilities_and_Interfaces_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/NASA Science Earth's Moon/'  where collection='/SMD/PDS_NASA_Science_Earths_Moon_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Wavelength/'  where collection='/SMD/nasa_wavelength/';
update @@ScienceMissionDirectorate set treepath='Earth Science/My NASA Data/'  where collection='/SMD/my_nasa_data/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mars Target Encyclopedia (MTE)/'  where collection='/SMD/mars_target_encyclopedia_mte/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Astrogeology Analysis Ready Data/'  where collection='/SMD/astrogeology_analysis_ready_data/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Interactive Multi-Instrument Database of Solar Flares/'  where collection='/SMD/interactive_multiinstrument_database_of_solar_flares/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Observer Publications/'  where collection='/SMD/earth_observer_publications/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Exoplanet Opacities Database/'  where collection='/SMD/exoplanet_opacities_database/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/GCN Circulars/'  where collection='/SMD/gcn_circulars/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Goddard Institute for Space Studies (GISS)/'  where collection='/SMD/goddard_institute_for_space_studies/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/IGWN Public Alerts User Guide/'  where collection='/SMD/igwn_public_alerts_user_guide/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Global Climate Change/'  where collection='/SMD/nasa_global_climate_change/';
update @@ScienceMissionDirectorate set treepath='Earth Science/GISS Publication List/'  where collection='/SMD/giss_publication_list/';
update @@ScienceMissionDirectorate set treepath='Earth Science/GISS Datasets and Derived Materials/'  where collection='/SMD/giss_datasets_and_derived_materials/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Our Changing Planet: The View from Space/'  where collection='/SMD/our_changing_planet_the_view_from_space_images/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA POWER/'  where collection='/SMD/nasa_power/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/EMAC: Exoplanet Modeling and Analysis Center/'  where collection='/SMD/emac_exoplanet_modeling_and_analysis_center/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/General Coordinates Network (GCN)/'  where collection='/SMD/general_coordinates_network_gcn/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/GCN Missions, Instruments and Facilities/'  where collection='/SMD/gcn_missions_instruments_and_facilities/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Science Decadal Surveys/'  where collection='/SMD/earth_science_decadal_surveys/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Algorithm Theoretical Basis Documents/'  where collection='/SMD/algorithm_theoretical_basis_documents/';
update @@ScienceMissionDirectorate set treepath='Earth Science/EOS Mission Page/'  where collection='/SMD/eos_mission_page/';
update @@ScienceMissionDirectorate set treepath='Earth Science/GISS Software Tools/'  where collection='/SMD/giss_software_tools/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Carbon Monitoring System/'  where collection='/SMD/nasa_carbon_monitoring_system/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/MAST Web Services/'  where collection='/SMD/mast_web_services/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/F' (F Prime)/'  where collection='/SMD/f_prime/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Observing Dashboard/'  where collection='/SMD/earth_observing_dashboard/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Fire Information for Resource Management System (FIRMS)/'  where collection='/SMD/fire_information_for_resource_management_system_firms/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA 2023 Climate Strategy/'  where collection='/SMD/nasa_2023_climate_strategy/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Extinction Calculator/'  where collection='/SMD/extinction_calculator/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Sea Level Change/'  where collection='/SMD/nasa_sea_level_change/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/High Level Science Products/'  where collection='/SMD/high_level_science_products/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/MAST Query/CasJobs/'  where collection='/SMD/mast_query_casjobs/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/exo.MAST/'  where collection='/SMD/exo_mast/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/MAST Portal/'  where collection='/SMD/mast_portal/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Virtual Observatory Information/'  where collection='/SMD/virtual_observatory_information/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Co-plotter/'  where collection='/SMD/co_plotter/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Z.MAST Search/'  where collection='/SMD/z_mast_search/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Astroquery API Search (MAST Queries)/'  where collection='/SMD/astroquery_api_search_mast_queries/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Pan-STARRS Catalog/'  where collection='/SMD/pan_starrs_catalog/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Pan-STARRS Catalog API/'  where collection='/SMD/pan_starrs_catalog_api/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Archived Synthetic Data/'  where collection='/SMD/archived_synthetic_data/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Skiff Spectral Catalog Search/'  where collection='/SMD/skiff_spectral_catalog_search/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Space Telescope Bibliographic Search/'  where collection='/SMD/space_telescope_bibliographic_search/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Montage Mosaic Engine/'  where collection='/SMD/montage_mosaic_engine/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/HEASARC Download Scripts/'  where collection='/SMD/heasarc_download_scripts/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/VAO Data Discovery DataScope/'  where collection='/SMD/vao_datascope/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Exoplanet Follow-up Observing Program/'  where collection='/SMD/exoplanet_follow_up_observing_program/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/MAST/'  where collection='/SMD/mast/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/NEID Archive/'  where collection='/SMD/neid_archive/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/LBTI Archive/'  where collection='/SMD/lbti_archive/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/CoRoT Exoplanet Archive-ETSS Data Sets/'  where collection='/SMD/corot_exoplanet_archive_etss_data_sets/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Contributed Datasets in the Exoplanet Archive/'  where collection='/SMD/contributed_datasets_in_the_exoplanet_archive/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/MAVEN ACC Data Search/'  where collection='/SMD/PDS_MAVEN_ACC_Data_Search/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/MAST Hubble Search/'  where collection='/SMD/mast_hubble_search/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Exoplanet Program Documents/'  where collection='/SMD/ASTRO_Exoplanet_Program_Documents_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Astromaterials Acquisition and Curation Office/'  where collection='/SMD/PDS_Astromaterials_Acquisition_and_Curation_Office_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/MAVEN NGIMS Data Search/'  where collection='/SMD/PDS_MAVEN_NGIMS_Data_Search/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/MAST Documentation/'  where collection='/SMD/ASTRO_MAST_Documentation_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Hubble Source Catalog Search API/'  where collection='/SMD/ASTRO_Hubble_Source_Catalog_Search_API_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Z.MAST API/'  where collection='/SMD/ASTRO_ZMAST_API_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/High-Resolution Transmission Molecular Absorption Database (HITRAN)/'  where collection='/SMD/PDS_High-Resolution_Transmission_Molecular_Absorption_Database_(HITRAN)_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Reducing Keck Data/'  where collection='/SMD/ASTRO_Data_Reduction_Tools_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/HEASARC Software/'  where collection='/SMD/ASTRO_HEASARC_Software_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Exoplanet API Search/'  where collection='/SMD/ASTRO_API_Search_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/High-Energy Missions/'  where collection='/SMD/ASTRO_High-Energy_Missions_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Missions and Data/'  where collection='/SMD/ASTRO_Missions_and_Data_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/NASA Space Science Data Coordinated Archive (NSSDCA)/'  where collection='/SMD/PDS_NASA_Space_Science_Data_Coordinated_Archive_(NSSDCA)_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/HIRES PRV/'  where collection='/SMD/ASTRO_HIRES_PRV_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/NASA Exoplanet Archive Documents/'  where collection='/SMD/ASTRO_NASA_Exoplanet_Archive_Documents_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Exoplanet TAP Search/'  where collection='/SMD/ASTRO_TAP_Search_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Java Mission-planning and Analysis for Remote Sensing (JMARS)/'  where collection='/SMD/PDS_Java_Mission-planning_and_Analysis_for_Remote_Sensing_(JMARS)_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/NASA GSFC HEASARC/'  where collection='/SMD/ASTRO_NAVO_HEASARC/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/ISIS: Integrated Software for Imagers and Spectrometers/'  where collection='/SMD/PDS_ISIS_Astro_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Ring-Moon Systems Node On-line Tools/'  where collection='/SMD/PDS_Ring-Moon_Systems_Node_On-line_Tools_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mars Exploration Program/'  where collection='/SMD/PDS_Mars_Exploration_Program_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/NASA's Eyes/'  where collection='/SMD/PDS_NASAs_Eyes_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PPI Models and Simulations Data Holdings/'  where collection='/SMD/PDS_Annex_Data_Holdings_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Planetary Plasma Interactions Software/'  where collection='/SMD/PDS_PPI_Software_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS Software, Tools, Tutorial, and Viewers/'  where collection='/SMD/PDS_Imaging_Software_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Pluto and Arrokoth Data Archive/'  where collection='/SMD/PDS_Pluto_and_Arrokoth_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Near Earth Asteroid Rendezvous (NEAR) Data Archive/'  where collection='/SMD/PDS_Near_Earth_Asteroid_Rendezvous_(NEAR)_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Atmospheric Escape Chemistry Page/'  where collection='/SMD/PDS_Atmospheric_Escape_Chemistry_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Neptune Archive Page/'  where collection='/SMD/PDS_Neptune_Archive_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Jupiter Data Archive/'  where collection='/SMD/PDS_Jupiter_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mars Lander Data/'  where collection='/SMD/PDS_Mars_Lander_Data_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Lunar Atmospheres Data Archive/'  where collection='/SMD/PDS_Lunar_Atmospheres_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Titan Data Archive/'  where collection='/SMD/PDS_Titan_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Saturn Data Archive/'  where collection='/SMD/PDS_Saturn_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Outer Planets Icy Satellites Archive Page/'  where collection='/SMD/PDS_Outer_Planets_Icy_Satellites_Archive_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Juno Archive Page/'  where collection='/SMD/PDS_Juno_Archive_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mercury Data Archive/'  where collection='/SMD/PDS_Mercury_Data_Archive_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Atmospheres Current Missions/'  where collection='/SMD/PDS_Current_Missions_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Messenger MASCS UVVS Archive Page/'  where collection='/SMD/PDS_Messenger_MASCS_UVVS_Archive_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mars GCM/'  where collection='/SMD/PDS_Mars_GCM_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Small Bodies Image Browser/'  where collection='/SMD/PDS_Small_Bodies_Image_Browser_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Analyst's Notebook/'  where collection='/SMD/PDS_Analyst_Notebook_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Geosciences Node Data Holdings/'  where collection='/SMD/PDS_Geosciences_Data_Holdings_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Virtual Astronaut/'  where collection='/SMD/PDS_Virtual_Astronaut_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Orbital Data Explorer REST Service/'  where collection='/SMD/PDS_ODE_REST_Service_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/TES Data Tool/'  where collection='/SMD/PDS_TES_Data_Node_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS Geosciences Node Spectral Library/'  where collection='/SMD/PDS_Geosciences_Node_Spectral_Library_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Lunar Orbiter Data Explorer/'  where collection='/SMD/PDS_Lunar_Orbiter_Data_Explorer_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Lunar Reconnaissance Orbiter's Lunar Orbiter Laser Altimeter (LOLA) RDR Query V2.0/'  where collection='/SMD/PDS_LOLA_RDR_Query_V20_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/DIVINER RDR Query/'  where collection='/SMD/PDS_DIVINER_RDR_Query_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mars Orbital Data Explorer/'  where collection='/SMD/PDS_Mars_Orbital_Data_Explorer_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Lunar Reconnaissance Orbiter's Lunar Orbiter Laser Altimeter (LOLA) RDR Query/'  where collection='/SMD/PDS_LOLA_RDR_Query_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS Tool Registry/'  where collection='/SMD/PDS_PDS_Tool_Registry_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS4 JParser/'  where collection='/SMD/PDS_PDS4_JParser_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS4 Local Data Dictionary Tool/'  where collection='/SMD/PDS_PDS4_Local_Data_Dictionary_Tool_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Mercury Orbital Data Explorer/'  where collection='/SMD/PDS_Mercury_Orbital_Data_Explorer_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Venus Orbital Data Explorer/'  where collection='/SMD/PDS_Venus_Orbital_Data_Explorer_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Photojournal/'  where collection='/SMD/PDS_Photojournal_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/CRISM Spectral Library/'  where collection='/SMD/PDS_CRISM_Spectral_Library_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Metadata Injector for PDS Labels/'  where collection='/SMD/PDS_Metadata_Injector_for_PDS_Labels_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS3 Standards Reference/'  where collection='/SMD/PDS_PDS3_Standards_Reference_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Data Portal/'  where collection='/SMD/PDS_Data_Portal_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/ARSET Applied Sciences/'  where collection='/SMD/ARSETAppliedSciences/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Science Suborbital Campaigns/'  where collection='/SMD/CASEI_Campaign/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Science Suborbital Platforms/'  where collection='/SMD/CASEI_Platform/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Science Data (CMR)/'  where collection='/SMD/CMR_API/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NTRS Publication Database/'  where collection='/SMD/NTRS/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Autoplot/'  where collection='/SMD/Autoplot_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/CEOS Missions/'  where collection='/SMD/CEOS_API_M/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Community Coordinated Modeling Center (CCMC)/'  where collection='/SMD/CCMC_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Earth Science Suborbital Instruments/'  where collection='/SMD/CASEI_Instrument/';
update @@ScienceMissionDirectorate set treepath='Earth Science/EarthData Pathfinders/'  where collection='/SMD/DataPathFinder/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Earth Observations/'  where collection='/SMD/NASA_Earth_Observations/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/SPASE Data Model/'  where collection='/SMD/SPASE_Website/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Helioviewer/'  where collection='/SMD/Helioviewer_Website/';
update @@ScienceMissionDirectorate set treepath='Biological and Physical Sciences/GeneLab Github Training/'  where collection='/SMD/GENELAB_Github_Training/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/SPEDAS/'  where collection='/SMD/SPEDAS_Website/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Heliophysics Events Knowledgebase/'  where collection='/SMD/Helio_Events_Knowledgebase_Website/';
update @@ScienceMissionDirectorate set treepath='Biological and Physical Sciences/GeneLab Github Sample Processing/'  where collection='/SMD/GENELAB_Github_SampleProcessing/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/PyHC/'  where collection='/SMD/PyHC_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Planck Cutout Visualization/'  where collection='/SMD/ASTRO_Planck_Cutout_Visualization_Website/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/WISE Image Service/'  where collection='/SMD/ASTRO_WISE_Image_Service_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Airborne Inventory/'  where collection='/SMD/CASEI/';
update @@ScienceMissionDirectorate set treepath='Earth Science/CODE NASA/'  where collection='/SMD/CODE_NASA_API/';
update @@ScienceMissionDirectorate set treepath='Earth Science/ESSCOR/'  where collection='/SMD/ESSCOR_API/';
update @@ScienceMissionDirectorate set treepath='Earth Science/GCIS ARTICLE/'  where collection='/SMD/GCIS_ARTICLE_API/';
update @@ScienceMissionDirectorate set treepath='Earth Science/GCIS BOOKS/'  where collection='/SMD/GCIS_BOOKS_API/';
update @@ScienceMissionDirectorate set treepath='Earth Science/GCIS JOURNAL/'  where collection='/SMD/GCIS_JOURNAL_API/';
update @@ScienceMissionDirectorate set treepath='Earth Science/GCIS REPORTS/'  where collection='/SMD/GCIS_REPORTS_API/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Archive Navigator/'  where collection='/SMD/PDS_Archive_Navigator_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Astrogeology/'  where collection='/SMD/PDS_Astrogeology_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Cassini Resource Page/'  where collection='/SMD/PDS_Cassini_Resource_Page_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/CRISM Analysis Toolkit (CAT)/'  where collection='/SMD/PDS_CRISM_Analysis_Toolkit_(CAT)_Website/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/JHelioviewer/'  where collection='/SMD/Helioviewer_Documentation_Website/';
update @@ScienceMissionDirectorate set treepath='Biological and Physical Sciences/Life Sciences Data Archive (LSDA)/'  where collection='/SMD/LSDA_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/PDS Small Bodies Node Asteroid Dust Subnode/'  where collection='/SMD/PDS_PDS_Small_Bodies_Node_Asteroid_Dust_Subnode_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Users' Guides/'  where collection='/SMD/PDS_Users_Guides_Website/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/TASKBOOK/'  where collection='/SMD/TASKBOOK_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Space Place/'  where collection='/SMD/Space_Place/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Sea Level Change/'  where collection='/SMD/Sea_Level_Change/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Earth Observatory/'  where collection='/SMD/NASA_Earth_Observatory/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA's Black Marble/'  where collection='/SMD/NASA_Black_Marble/';
update @@ScienceMissionDirectorate set treepath='Earth Science/SERVIR Global/'  where collection='/SMD/SERVIR_Global/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA SPoRT/'  where collection='/SMD/NASA_SPoRT/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Climate Change/'  where collection='/SMD/NASA_Climate_Change/';
update @@ScienceMissionDirectorate set treepath='Biological and Physical Sciences/Space Biology Science Digest/'  where collection='/SMD/Space_Biology_Science_Digest/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Optical Constants Database/'  where collection='/SMD/Optical_Constants_Database/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Small Bodies Node/'  where collection='/SMD/Small_Bodies_Node/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Solar Physics Group/'  where collection='/SMD/Solar_Physics_Group/';
update @@ScienceMissionDirectorate set treepath='Planetary Science/Outer Planets Unified Search (OPUS)/'  where collection='/SMD/PDS_OPUS_Website/';
update @@ScienceMissionDirectorate set treepath='Earth Science/VEDA STAC Catalog/'  where collection='/SMD/VEDA_STAC_Catalog/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Commercial Smallsat Data Acquisition (CSDA) Program/'  where collection='/SMD/Commercial_Smallsat_Data_Acquisition_CSDA_Program/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Space Physics Data Facility/'  where collection='/SMD/Space_Physics_Data_Facility/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/NASA's Heliophysics Digital Resource Library (HDRL)/'  where collection='/SMD/NASA_Heliophysics_Digital_Resource_Library_HDRL/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Worldview/'  where collection='/SMD/NASA_Worldview/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Techport/'  where collection='/SMD/NASA_Techport/';
update @@ScienceMissionDirectorate set treepath='Earth Science/NASA Earthdata/'  where collection='/SMD/NASA_Earthdata/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Heliophysics Project Data Management Plans/'  where collection='/SMD/Heliophysics_Project_Data_Management_Plans/';
update @@ScienceMissionDirectorate set treepath='Astrophysics/Fake Collection for Testing/'  where collection='/SMD/fake_collection_for_testing/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Algorithm Publication Tool/'  where collection='/SMD/Algorithm_Publication_Tool/';
update @@ScienceMissionDirectorate set treepath='Earth Science/Socioeconomic Data and Applications Center (SEDAC)/'  where collection='/SMD/Socioeconomic_Data_and_Applications_Center_SEDAC/';
update @@ScienceMissionDirectorate set treepath='Heliophysics/Solar Data Analysis Center (SDAC)/'  where collection='/SMD/Solar_Data_Analysis_Center_SDAC/';
update @@ScienceMissionDirectorate set treepath='Earth Science/VEDA Dashboard/'  where collection='/SMD/VEDA_Dashboard/';
