# Generated by Django 4.0.10 on 2023-03-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="config_folder",
            field=models.CharField(
                default="", max_length=2048, verbose_name="Config Folder"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collection",
            name="turned_on",
            field=models.BooleanField(default=True, verbose_name="Turned On"),
        ),
        migrations.AddField(
            model_name="collection",
            name="url",
            field=models.URLField(max_length=2048, verbose_name="URL"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collection",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sde_collections.division",
            ),
            preserve_default=False,
        ),
    ]
