# Generated by Django 4.2 on 2023-05-10 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="machine_name",
        ),
    ]
