# Generated by Django 4.0.10 on 2023-03-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0003_candidateurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateurl',
            name='url',
            field=models.CharField(default='', max_length=2048, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
