# Generated by Django 4.2 on 2023-05-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0003_alter_collection_config_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="cleaning_order",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
