# Generated by Django 4.2 on 2023-05-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0004_collection_cleaning_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateurl",
            name="url",
            field=models.CharField(verbose_name="URL"),
        ),
    ]
