# Generated by Django 4.0.10 on 2023-03-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0004_candidateurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='candidateurl',
            options={'verbose_name': 'Candidate URL', 'verbose_name_plural': 'Candidate URLs'},
        ),
    ]
