# Generated by Django 4.2 on 2023-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0005_alter_candidateurl_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateurl",
            name="generated_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title generated based on a Title Pattern",
                verbose_name="Generated Title",
            ),
        ),
        migrations.AlterField(
            model_name="candidateurl",
            name="scraped_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the original title scraped by Sinequa",
                verbose_name="Scraped Title",
            ),
        ),
    ]
