# Generated by Django 4.0.10 on 2023-03-28 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0006_scrapedurl_remove_candidateurl_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(max_length=2048, verbose_name='URL')),
                ('excluded', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde_collections.collection')),
            ],
            options={
                'verbose_name': 'Candidate URL',
                'verbose_name_plural': 'Candidate URLs',
            },
        ),
        migrations.DeleteModel(
            name='ScrapedURL',
        ),
    ]
