# Generated by Django 4.2 on 2023-05-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0006_alter_candidateurl_generated_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="excludepattern",
            name="pattern_type",
            field=models.IntegerField(
                choices=[(1, "Individual URL"), (2, "Regex Pattern")], default=1
            ),
        ),
    ]
