# Generated by Django 4.0.10 on 2023-03-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0007_candidateurl_delete_scrapedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateurl',
            name='title',
            field=models.CharField(default='', max_length=2048, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
