# Generated by Django 4.2 on 2023-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0007_excludepattern_pattern_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excludepattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all the documents in the collection and documents with a matching URL are excluded.",
                verbose_name="Pattern",
            ),
        ),
    ]
