# Generated by Django 4.2 on 2023-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0008_alter_excludepattern_match_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlepattern",
            name="pattern_type",
            field=models.IntegerField(
                choices=[(1, "Individual URL"), (2, "Regex Pattern")], default=1
            ),
        ),
    ]
