# Generated by Django 4.2 on 2023-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0009_titlepattern_pattern_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="titlepattern",
            old_name="pattern_type",
            new_name="match_pattern_type",
        ),
        migrations.AddField(
            model_name="titlepattern",
            name="title_pattern_type",
            field=models.IntegerField(
                choices=[(1, "Plain Text"), (2, "Python"), (3, "Xpath")], default=1
            ),
        ),
    ]
