# Generated by Django 4.0.10 on 2023-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0009_collection_audit_duplicate_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='source',
            field=models.IntegerField(choices=[(1, 'Only in original'), (2, 'Both'), (3, 'Only in Sinequa configs')]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='update_frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Biweekly'), (4, 'Monthly')], default=2),
        ),
    ]
