# Generated by Django 4.0.10 on 2023-03-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0011_alter_collection_audit_duplicate_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidateurl',
            name='title',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Title'),
        ),
    ]
