# Generated by Django 4.2 on 2023-05-15 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sde_collections", "0011_alter_titlepattern_title_pattern_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="curated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="curation_started",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Curation Started"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="curation_status",
            field=models.IntegerField(
                choices=[(1, "Backlog"), (2, "Being Curated"), (3, "Done")], default=1
            ),
        ),
    ]
