# Generated by Django 4.2 on 2023-05-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "sde_collections",
            "0012_collection_curated_by_collection_curation_started_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titlepattern",
            options={
                "verbose_name": "Title Pattern",
                "verbose_name_plural": "Title Patterns",
            },
        ),
        migrations.AlterUniqueTogether(
            name="excludepattern",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="titlepattern",
            name="title_pattern_type",
        ),
        migrations.AddField(
            model_name="excludepattern",
            name="match_pattern_type",
            field=models.IntegerField(
                choices=[
                    (1, "Individual URL"),
                    (2, "Regex Pattern"),
                    (3, "Xpath Pattern"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="titlepattern",
            name="candidate_urls",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_urls",
                related_query_name="%(app_label)s_%(class)ss",
                to="sde_collections.candidateurl",
            ),
        ),
        migrations.AlterField(
            model_name="excludepattern",
            name="candidate_urls",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_urls",
                related_query_name="%(app_label)s_%(class)ss",
                to="sde_collections.candidateurl",
            ),
        ),
        migrations.AlterField(
            model_name="excludepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_pattern",
                related_query_name="%(app_label)s_%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="excludepattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all the documents in the collection and matching documents will be returned",
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_pattern",
                related_query_name="%(app_label)s_%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all the documents in the collection and matching documents will be returned",
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="match_pattern_type",
            field=models.IntegerField(
                choices=[
                    (1, "Individual URL"),
                    (2, "Regex Pattern"),
                    (3, "Xpath Pattern"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="title_pattern",
            field=models.CharField(
                help_text="This is the pattern for the new title. You can write your own text, as well as add references to a specific xpath or the orignal title. For example 'James Webb {scraped_title}: {xpath}'",
                verbose_name="Title Pattern",
            ),
        ),
        migrations.CreateModel(
            name="DocumentTypePattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_pattern",
                    models.CharField(
                        help_text="This pattern is compared against the URL of all the documents in the collection and matching documents will be returned",
                        verbose_name="Pattern",
                    ),
                ),
                (
                    "match_pattern_type",
                    models.IntegerField(
                        choices=[
                            (1, "Individual URL"),
                            (2, "Regex Pattern"),
                            (3, "Xpath Pattern"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (1, "Images"),
                            (2, "Data"),
                            (3, "Documentation"),
                            (4, "Software and Tools"),
                            (5, "Missions and Instruments"),
                        ]
                    ),
                ),
                (
                    "candidate_urls",
                    models.ManyToManyField(
                        related_name="%(app_label)s_%(class)s_urls",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="sde_collections.candidateurl",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_pattern",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Type Pattern",
                "verbose_name_plural": "Document Type Patterns",
            },
        ),
        migrations.RemoveField(
            model_name="excludepattern",
            name="pattern_type",
        ),
    ]
