# Generated by Django 4.0.10 on 2023-03-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0012_collection_updated_at_alter_candidateurl_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
