# Generated by Django 4.2 on 2023-05-16 03:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0013_alter_titlepattern_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documenttypepattern",
            unique_together={("collection", "match_pattern")},
        ),
        migrations.AlterUniqueTogether(
            name="excludepattern",
            unique_together={("collection", "match_pattern")},
        ),
        migrations.AlterUniqueTogether(
            name="titlepattern",
            unique_together={("collection", "match_pattern")},
        ),
    ]
