# Generated by Django 4.0.10 on 2023-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0013_alter_collection_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='URL'),
        ),
    ]
