# Generated by Django 4.0.10 on 2023-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0014_alter_collection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='connector',
            field=models.IntegerField(choices=[(1, 'Web crawler paralle')], default=1),
        ),
    ]
