# Generated by Django 4.2 on 2023-05-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0015_candidateurl_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttypepattern",
            name="candidate_urls",
            field=models.ManyToManyField(
                related_name="%(class)s_urls", to="sde_collections.candidateurl"
            ),
        ),
        migrations.AlterField(
            model_name="documenttypepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="excludepattern",
            name="candidate_urls",
            field=models.ManyToManyField(
                related_name="%(class)s_urls", to="sde_collections.candidateurl"
            ),
        ),
        migrations.AlterField(
            model_name="excludepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="candidate_urls",
            field=models.ManyToManyField(
                related_name="%(class)s_urls", to="sde_collections.candidateurl"
            ),
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
    ]
