# Generated by Django 4.0.10 on 2023-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0015_collection_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateurl',
            name='full_url',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Full URL'),
        ),
    ]
