# Generated by Django 4.0.10 on 2023-04-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0016_candidateurl_full_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=2048, verbose_name='Pattern')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclude_patterns', to='sde_collections.collection')),
            ],
            options={
                'verbose_name': 'Exclude Pattern',
                'verbose_name_plural': 'Exclude Patterns',
            },
        ),
    ]
