# Generated by Django 4.2.1 on 2023-05-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0016_alter_documenttypepattern_candidate_urls_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Url which is expected to be brought in by the scraper and indexer",
                        max_length=512,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sde_collections.collection",
                    ),
                ),
            ],
        ),
    ]
