# Generated by Django 4.0.10 on 2023-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0017_excludepattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludepattern',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Reason for excluding'),
        ),
    ]
