# Generated by Django 4.2.1 on 2023-05-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0017_requiredurls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requiredurls",
            name="url",
            field=models.URLField(
                help_text="Url which is expected to be brought in by the scraper and indexer"
            ),
        ),
    ]
