# Generated by Django 4.2 on 2023-05-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0018_alter_requiredurls_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requiredurls",
            name="url",
            field=models.URLField(
                help_text="URL which is expected to be brought in by the scraper and indexer"
            ),
        ),
    ]
