# Generated by Django 4.0.10 on 2023-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0018_excludepattern_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateurl',
            name='replacement_title',
            field=models.CharField(blank=True, default='', help_text='If set, this title will be used instead of the scraped title. You can use the original title in the replacement title like so: {title}.', max_length=2048, verbose_name='Replacement Title'),
        ),
    ]
