# Generated by Django 4.2 on 2023-05-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0019_alter_requiredurls_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="curation_status",
            field=models.IntegerField(
                choices=[
                    (1, "Needs Scraping"),
                    (2, "Ready to Curate"),
                    (3, "Being Curated"),
                    (4, "Curated"),
                    (5, "In Production"),
                ],
                default=1,
            ),
        ),
    ]
