# Generated by Django 4.2.1 on 2023-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0020_alter_collection_curation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="curation_status",
            field=models.IntegerField(
                choices=[
                    (1, "Needs Scraping"),
                    (2, "Ready to Curate"),
                    (3, "Being Curated"),
                    (4, "Needs Rescraping"),
                    (5, "Curated"),
                    (6, "In Production"),
                ],
                default=1,
            ),
        ),
    ]
