# Generated by Django 4.2 on 2023-05-28 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0021_alter_collection_curation_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidateurl",
            unique_together={("collection", "url")},
        ),
    ]
