# Generated by Django 4.0.10 on 2023-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0021_alter_candidateurl_replacement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateurl',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='candidateurl',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='candidateurl',
            name='path',
        ),
        migrations.AlterField(
            model_name='candidateurl',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Path'),
        ),
    ]
