# Generated by Django 4.2 on 2023-04-20 18:11

from django.db import migrations, models


def update_machine_names(apps, schema_editor):
    Collection = apps.get_model("your_app_name", "Collection")
    for collection in Collection.objects.all():
        collection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0021_alter_candidateurl_replacement_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="machine_name",
            field=models.CharField(
                default="",
                help_text="This is the Name value, but with only alphanumeric characters and _ instead of spaces",
                max_length=1024,
                verbose_name="Machine Name",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(update_machine_names),
    ]
