# Generated by Django 4.2 on 2023-06-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0022_alter_candidateurl_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="github_issue_number",
            field=models.IntegerField(default=0, verbose_name="Issue Number in Github"),
        ),
    ]
