# Generated by Django 4.0.10 on 2023-04-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0022_remove_candidateurl_depth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateurl',
            options={'ordering': ['url'], 'verbose_name': 'Candidate URL', 'verbose_name_plural': 'Candidate URLs'},
        ),
    ]
