# Generated by Django 4.2.1 on 2023-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0023_collection_github_issue_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="curation_status",
            field=models.IntegerField(
                choices=[
                    (1, "Needs Scraping"),
                    (2, "Ready to Curate"),
                    (3, "Being Curated"),
                    (7, "Delete/Combine Collection"),
                    (4, "Needs Rescraping"),
                    (5, "Curated"),
                    (6, "In Production"),
                ],
                default=1,
            ),
        ),
    ]
