# Generated by Django 4.2 on 2023-04-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0024_candidateurl_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="connector",
            field=models.IntegerField(choices=[(1, "Web crawler parallel")], default=1),
        ),
    ]
