# Generated by Django 4.0.10 on 2023-04-25 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde_collections', '0025_alter_collection_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateurl',
            name='excluded',
        ),
        migrations.RemoveField(
            model_name='candidateurl',
            name='full_url',
        ),
        migrations.RemoveField(
            model_name='candidateurl',
            name='replacement_title',
        ),
        migrations.RemoveField(
            model_name='candidateurl',
            name='title',
        ),
        migrations.RemoveField(
            model_name='excludepattern',
            name='pattern',
        ),
        migrations.AddField(
            model_name='candidateurl',
            name='generated_title',
            field=models.CharField(blank=True, default='', help_text='This is the title generated based on a Title Pattern', max_length=2048, verbose_name='Generated Title'),
        ),
        migrations.AddField(
            model_name='candidateurl',
            name='scraped_title',
            field=models.CharField(blank=True, default='', help_text='This is the original title scraped by Sinequa', max_length=2048, verbose_name='Scraped Title'),
        ),
        migrations.AddField(
            model_name='excludepattern',
            name='match_pattern',
            field=models.CharField(default='', help_text='This pattern is compared against the URL of all the documents in the collection and documents with a matching URL are excluded.', max_length=2048, verbose_name='Pattern'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateurl',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='TitlePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_pattern', models.CharField(help_text='This pattern is compared against the URL of all the documents in the collection and matching documents will have their title overwritten with the title_pattern', max_length=2048, verbose_name='Pattern')),
                ('title_pattern', models.CharField(help_text="This is the pattern for the new title. You can write your own text, as well as add references to a specific xpath or the orignal title. For example 'James Webb {scraped_title}: {xpath}'", max_length=2048, verbose_name='New Title Pattern')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_patterns', to='sde_collections.collection')),
            ],
            options={
                'verbose_name': 'Title Re-Write Pattern',
                'verbose_name_plural': 'Title Re-Write Patterns',
            },
        ),
    ]
