# Generated by Django 4.2.2 on 2023-06-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sde_collections",
            "0025_alter_documenttypepattern_match_pattern_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="curation_status",
            field=models.IntegerField(
                choices=[
                    (1, "Needs Scraping"),
                    (2, "Ready to Curate"),
                    (3, "Being Curated"),
                    (7, "Delete/Combine Collection"),
                    (4, "Needs Rescraping"),
                    (5, "Curated"),
                    (8, "GitHub PR Created"),
                    (6, "In Production"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="title_pattern",
            field=models.CharField(
                help_text="This is the pattern for the new title. You can either write an exact replacement string (no quotes required) or you can write sinequa-valid code",
                verbose_name="Title Pattern",
            ),
        ),
    ]
