# Generated by Django 4.2 on 2023-04-25 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0026_remove_candidateurl_excluded_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateurl",
            name="level",
        ),
    ]
