# Generated by Django 4.2 on 2023-04-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0027_remove_candidateurl_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="level",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Level in the tree. Based on /.",
                verbose_name="Level",
            ),
        ),
    ]
