# Generated by Django 4.2.2 on 2023-06-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0027_alter_collection_connector"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="has_sinequa_config",
            field=models.BooleanField(default=True),
        ),
    ]
