# Generated by Django 4.2.3 on 2023-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0028_collection_has_sinequa_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateurl",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (1, "Images"),
                    (2, "Data"),
                    (3, "Documentation"),
                    (4, "Software and Tools"),
                    (5, "Missions and Instruments"),
                    (6, "Training and Education"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="document_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Images"),
                    (2, "Data"),
                    (3, "Documentation"),
                    (4, "Software and Tools"),
                    (5, "Missions and Instruments"),
                    (6, "Training and Education"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documenttypepattern",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (1, "Images"),
                    (2, "Data"),
                    (3, "Documentation"),
                    (4, "Software and Tools"),
                    (5, "Missions and Instruments"),
                    (6, "Training and Education"),
                ]
            ),
        ),
    ]
