# Generated by Django 4.2 on 2023-04-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0029_alter_candidateurl_collection_appliedexclude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedexclude",
            name="candidate_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applied_excludes",
                to="sde_collections.candidateurl",
            ),
        ),
        migrations.AlterField(
            model_name="appliedexclude",
            name="exclude_pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applied_excludes",
                to="sde_collections.excludepattern",
            ),
        ),
    ]
