# Generated by Django 4.2 on 2023-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0030_alter_appliedexclude_candidate_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="excludes",
            field=models.ManyToManyField(
                blank=True,
                through="sde_collections.AppliedExclude",
                to="sde_collections.excludepattern",
            ),
        ),
    ]
