# Generated by Django 4.2.3 on 2023-09-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0031_candidateurl_is_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="workflow_status",
            field=models.IntegerField(
                choices=[
                    (1, "Collection Created"),
                    (2, "Unengineered"),
                    (3, "Engineering In Progress"),
                    (4, "Engineering Completed But No URL's Yet"),
                    (5, "URL'S Generated"),
                    (6, "Ready For Curation"),
                    (7, "Being Curated"),
                    (8, "Curated"),
                    (9, "Final Code Reviewed"),
                    (10, "Deployed To Test"),
                    (11, "Completed Running On Test Server"),
                    (12, "Quality Check In Progress"),
                    (13, "Quality Check Completed"),
                    (14, "Deployed To Production"),
                    (15, "Finished Running on Production"),
                ],
                default=1,
            ),
        ),
    ]
