# Generated by Django 4.2.3 on 2023-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0031_candidateurl_is_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="workflow_status",
            field=models.IntegerField(
                choices=[
                    (1, "Research in Progress"),
                    (2, "Config Created"),
                    (3, "Engineering in Progress"),
                    (4, "Engineering Completed"),
                    (5, "URLs Generated and Ready to Curate"),
                    (6, "Curation in Progress"),
                    (7, "Curated"),
                    (8, "Curation Code Reviewed"),
                    (9, "Test Deployment Completed"),
                    (10, "Test Indexing Completed"),
                    (11, "Test Quality Checks in Progress"),
                    (12, "Test Quality Checks Completed"),
                    (13, "Production Deployment Completed"),
                    (14, "Production Indexing Completed"),
                    (15, "Production Quality Checks in Progress"),
                    (16, "Production Quality Checks Completed"),
                ],
                default=1,
            ),
        ),
    ]
