# Generated by Django 4.2.3 on 2023-10-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0032_collection_workflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="workflow_status",
            field=models.IntegerField(
                choices=[
                    (1, "Collection Created"),
                    (2, "Unengineered"),
                    (3, "Engineering In Progress"),
                    (4, "Engineering Completed But No URL's Yet"),
                    (5, "URL'S Generated and Ready to Curate"),
                    (6, "Curation in Progress"),
                    (7, "Curated"),
                    (8, "Final Code Reviewed"),
                    (9, "Deployed To Test"),
                    (10, "Completed Running On Test Server"),
                    (11, "Quality Check In Progress"),
                    (12, "Quality Check Completed"),
                    (13, "Deployed To Production"),
                    (14, "Finished Running on Production"),
                ],
                default=1,
            ),
        ),
    ]
