# Generated by Django 4.2.6 on 2023-10-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0032_collection_workflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="config_folder",
            field=models.CharField(
                editable=False,
                max_length=2048,
                unique=True,
                verbose_name="Config Folder",
            ),
        ),
    ]
