# Generated by Django 4.2 on 2023-04-28 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0032_alter_appliedexclude_candidate_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="excludepattern",
            unique_together={("collection", "match_pattern")},
        ),
    ]
