# Generated by Django 4.2 on 2023-05-09 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0027_machine_name"),
        ("sde_collections", "0033_alter_excludepattern_unique_together"),
    ]

    operations = []
