# Generated by Django 4.2.6 on 2023-10-18 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0033_alter_collection_config_folder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="tree_root",
            new_name="tree_root_deprecated",
        ),
    ]
