# Generated by Django 4.2 on 2023-05-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0034_merge_20230508_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="new_collection",
            field=models.BooleanField(default=False),
        ),
    ]
