# Generated by Django 4.2.6 on 2023-10-18 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0034_rename_tree_root_collection_tree_root_deprecated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidateurl",
            unique_together=set(),
        ),
    ]
