# Generated by Django 4.2 on 2023-05-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0035_collection_new_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="excludepattern",
            name="candidate_urls",
            field=models.ManyToManyField(
                through="sde_collections.AppliedExclude",
                to="sde_collections.candidateurl",
            ),
        ),
    ]
