# Generated by Django 4.2.6 on 2023-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0035_alter_candidateurl_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="present_on_prod",
            field=models.BooleanField(
                default=False,
                help_text="Helps keep track if the Current URL is present in production or not",
                verbose_name="URL Present In Production?",
            ),
        ),
        migrations.AddField(
            model_name="candidateurl",
            name="present_on_test",
            field=models.BooleanField(
                default=False,
                help_text="Helps keep track if the Current URL is present in test environment or not",
                verbose_name="URL Present In Test Environment?",
            ),
        ),
        migrations.AddField(
            model_name="candidateurl",
            name="production_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title present on Production Server",
                verbose_name="Title on Production Server",
            ),
        ),
        migrations.AddField(
            model_name="candidateurl",
            name="test_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title present on Test Server",
                verbose_name="Title on Test Server",
            ),
        ),
    ]
