# Generated by Django 4.2.6 on 2023-10-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0035_alter_candidateurl_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="present_on_prod",
            field=models.BooleanField(
                default=False,
                help_text="Helps keep track if the Current URL is present in production or not",
                verbose_name="URL Present In Production?",
            ),
        ),
        migrations.AddField(
            model_name="candidateurl",
            name="present_on_test",
            field=models.BooleanField(
                default=False,
                help_text="Helps keep track if the Current URL is present in test environment or not",
                verbose_name="URL Present In Test Environment?",
            ),
        ),
    ]
