# Generated by Django 4.2.6 on 2023-11-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0036_candidateurl_present_on_prod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="source",
            field=models.IntegerField(
                choices=[
                    (1, "Only in original"),
                    (2, "Both"),
                    (3, "Only in Sinequa configs"),
                ],
                default=2,
            ),
        ),
    ]
