# Generated by Django 4.2 on 2023-05-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0036_excludepattern_candidate_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="visited",
            field=models.BooleanField(default=False),
        ),
    ]
