# Generated by Django 4.2.6 on 2023-10-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0036_candidateurl_present_on_prod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="production_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title present on Production Server",
                verbose_name="Title on Production Server",
            ),
        ),
        migrations.AddField(
            model_name="candidateurl",
            name="test_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title present on Test Server",
                verbose_name="Title on Test Server",
            ),
        ),
    ]
