# Generated by Django 4.2.6 on 2023-11-26 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0037_alter_collection_source"),
        ("sde_collections", "0037_remove_collection_has_sinequa_config"),
    ]

    operations = []
