# Generated by Django 4.2.6 on 2023-11-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0038_merge_20231126_1152"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncludePattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_pattern",
                    models.CharField(
                        help_text="This pattern is compared against the URL of all the documents in the collection and matching documents will be returned",
                        verbose_name="Pattern",
                    ),
                ),
                (
                    "match_pattern_type",
                    models.IntegerField(
                        choices=[
                            (1, "Individual URL Pattern"),
                            (2, "Multi-URL Pattern"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "candidate_urls",
                    models.ManyToManyField(
                        related_name="%(class)s_urls", to="sde_collections.candidateurl"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        related_query_name="%(class)ss",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Include Pattern",
                "verbose_name_plural": "Include Patterns",
                "unique_together": {("collection", "match_pattern")},
            },
        ),
    ]
