# Generated by Django 4.2.6 on 2023-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0039_includepattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="url_count_prod",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="url_count_secret_prod",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="url_count_secret_test",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="url_count_test",
            field=models.IntegerField(default=0),
        ),
    ]
