# Generated by Django 5.0.1 on 2024-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0039_includepattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="hash",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="Hash"
            ),
        ),
    ]
