# Generated by Django 4.2.6 on 2023-12-01 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0040_collection_url_count_prod_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="url_count_prod",
            new_name="url_count_production",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="url_count_secret_prod",
            new_name="url_count_secret_production",
        ),
    ]
