# Generated by Django 5.0.1 on 2024-02-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0041_alter_candidateurl_hash"),
        (
            "sde_collections",
            "0041_rename_url_count_prod_collection_url_count_production_and_more",
        ),
    ]

    operations = []
