# Generated by Django 5.0.1 on 2024-02-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0042_merge_20240219_1422"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="url_count_secret_production",
            new_name="url_count_dev",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="url_count_secret_test",
        ),
    ]
