# Generated by Django 4.2.9 on 2024-04-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0043_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (1, "Images"),
                    (2, "Data"),
                    (3, "Documentation"),
                    (4, "Software and Tools"),
                    (5, "Missions and Instruments"),
                    (6, "Training and Education"),
                ],
                default=3,
            ),
        ),
    ]
