# Generated by Django 4.2.9 on 2024-05-21 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0045_alter_collection_workflow_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolvedTitle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resolution_status",
                    models.BooleanField(default=False, help_text="True if resolved, False if unresolved"),
                ),
                ("resolution_date_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_title", models.CharField(blank=True, max_length=1024)),
                ("error_string", models.TextField(blank=True)),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                (
                    "candidate_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolved_titles",
                        to="sde_collections.candidateurl",
                    ),
                ),
                (
                    "title_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolved_titles",
                        to="sde_collections.titlepattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolved Title",
                "verbose_name_plural": "Resolved Titles",
            },
        ),
        migrations.AddField(
            model_name="candidateurl",
            name="resolved_title",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the resolved title data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_urls",
                to="sde_collections.resolvedtitle",
            ),
        ),
    ]
