# Generated by Django 4.2.9 on 2024-05-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0047_remove_candidateurl_resolved_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resolvedtitle",
            name="candidate_url",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolved_titles",
                to="sde_collections.candidateurl",
            ),
        ),
    ]
