# Generated by Django 4.2.9 on 2024-05-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0048_alter_resolvedtitle_candidate_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resolvedtitle",
            name="resolution_date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
