# Generated by Django 4.2.9 on 2024-05-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0051_alter_resolvedtitle_error_string_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resolvedtitle",
            old_name="resolution_date_time",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="resolvedtitle",
            name="error_string",
        ),
        migrations.RemoveField(
            model_name="resolvedtitle",
            name="http_status_code",
        ),
        migrations.RemoveField(
            model_name="resolvedtitle",
            name="resolution_status",
        ),
        migrations.AlterField(
            model_name="resolvedtitle",
            name="candidate_url",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="sde_collections.candidateurl"),
        ),
        migrations.AlterField(
            model_name="resolvedtitle",
            name="title_pattern",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sde_collections.titlepattern"),
        ),
        migrations.CreateModel(
            name="ResolvedTitleError",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error_string", models.TextField()),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                (
                    "candidate_url",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sde_collections.candidateurl"
                    ),
                ),
                (
                    "title_pattern",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sde_collections.titlepattern"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
