# Generated by Django 4.2.9 on 2024-05-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0052_rename_resolution_date_time_resolvedtitle_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="url",
            field=models.URLField(max_length=2048, verbose_name="URL"),
        ),
    ]
