# Generated by Django 4.2.9 on 2024-05-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0046_workflowhistory_old_status"),
        ("sde_collections", "0053_alter_collection_url"),
    ]

    operations = []
