# Generated by Django 4.2.9 on 2024-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0053_alter_collection_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
