# Generated by Django 4.2.9 on 2024-05-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0055_titlepattern_matched_urls_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="titlepattern",
            old_name="matched_urls",
            new_name="urls",
        ),
    ]
