# Generated by Django 4.2.9 on 2024-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0055_alter_workflowhistory_old_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateurl",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (1, "Images"),
                    (2, "Data"),
                    (3, "Documentation"),
                    (4, "Software and Tools"),
                    (5, "Missions and Instruments"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (1, "Images"),
                    (2, "Data"),
                    (3, "Documentation"),
                    (4, "Software and Tools"),
                    (5, "Missions and Instruments"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="documenttypepattern",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (1, "Images"),
                    (2, "Data"),
                    (3, "Documentation"),
                    (4, "Software and Tools"),
                    (5, "Missions and Instruments"),
                ]
            ),
        ),
    ]
