# Generated by Django 4.2.9 on 2024-05-23 22:09

from django.db import migrations, models
import sde_collections.models.pattern


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0056_rename_matched_urls_titlepattern_urls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resolvedtitle",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Resolved Title",
                "verbose_name_plural": "Resolved Titles",
            },
        ),
        migrations.AlterField(
            model_name="titlepattern",
            name="title_pattern",
            field=models.CharField(
                validators=[sde_collections.models.pattern.validate_title_pattern], verbose_name="Title Pattern"
            ),
        ),
    ]
