# Generated by Django 4.2.9 on 2024-10-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0058_candidateurl_division_collection_is_multi_division_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="tdamm_manual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="tdamm_ml",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
