# Generated by Django 4.2.9 on 2024-10-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0058_candidateurl_division_collection_is_multi_division_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateurl",
            name="scraped_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
