# Generated by Django 4.2.9 on 2024-10-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0058_candidateurl_division_collection_is_multi_division_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=4096, verbose_name="URL")),
                (
                    "scraped_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="This is the original title scraped by Sinequa",
                        max_length=1024,
                        verbose_name="Scraped Title",
                    ),
                ),
                (
                    "generated_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="This is the title generated based on a Title Pattern",
                        max_length=1024,
                        verbose_name="Generated Title",
                    ),
                ),
                ("visited", models.BooleanField(default=False)),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (1, "Images"),
                            (2, "Data"),
                            (3, "Documentation"),
                            (4, "Software and Tools"),
                            (5, "Missions and Instruments"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "division",
                    models.IntegerField(
                        choices=[
                            (1, "Astrophysics"),
                            (2, "Biological and Physical Sciences"),
                            (3, "Earth Science"),
                            (4, "Heliophysics"),
                            (5, "Planetary Science"),
                            (6, "General"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
                "ordering": ["url"],
            },
        ),
        migrations.CreateModel(
            name="CuratedUrl",
            fields=[
                (
                    "url_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sde_collections.url",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curated URL",
                "verbose_name_plural": "Curated URLs",
            },
            bases=("sde_collections.url",),
        ),
        migrations.CreateModel(
            name="DeltaUrl",
            fields=[
                (
                    "url_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sde_collections.url",
                    ),
                ),
                ("delete", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Delta URL",
                "verbose_name_plural": "Delta URLs",
            },
            bases=("sde_collections.url",),
        ),
        migrations.CreateModel(
            name="DumpUrl",
            fields=[
                (
                    "url_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sde_collections.url",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dump URL",
                "verbose_name_plural": "Dump URLs",
            },
            bases=("sde_collections.url",),
        ),
    ]
