# Generated by Django 4.2.9 on 2024-09-03 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0058_candidateurl_division_collection_is_multi_division_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="delete",
            new_name="deleteable",
        ),
    ]
