# Generated by Django 4.2.9 on 2024-10-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0059_url_curatedurl_deltaurl_dumpurl"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DumpUrl",
        ),
    ]
