# Generated by Django 4.2.9 on 2024-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0059_collection_tdamm_manual_collection_tdamm_ml"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="tdamm_manual",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="tdamm_ml",
        ),
        migrations.AddField(
            model_name="collection",
            name="tdamm_tag_manual",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="TDAMM Manual Tag"),
        ),
        migrations.AddField(
            model_name="collection",
            name="tdamm_tag_ml",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="TDAMM ML Tag"),
        ),
    ]
