# Generated by Django 4.2.9 on 2024-11-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0059_url_curatedurl_deltaurl_dumpurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deltaurl",
            name="url_ptr",
        ),
        migrations.RemoveField(
            model_name="dumpurl",
            name="url_ptr",
        ),
        migrations.RemoveField(
            model_name="url",
            name="collection",
        ),
        migrations.DeleteModel(
            name="CuratedUrl",
        ),
        migrations.DeleteModel(
            name="DeltaUrl",
        ),
        migrations.DeleteModel(
            name="DumpUrl",
        ),
        migrations.DeleteModel(
            name="Url",
        ),
    ]
