# Generated by Django 4.2.9 on 2024-11-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0060_remove_deltaurl_url_ptr_remove_dumpurl_url_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DumpUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(unique=True, verbose_name="Url")),
                ("scraped_title", models.CharField(blank=True, default="", verbose_name="Scraped Title")),
                ("generated_title", models.CharField(blank=True, default="", verbose_name="Generated Title")),
                ("visited", models.BooleanField(default=False)),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (1, "Images"),
                            (2, "Data"),
                            (3, "Documentation"),
                            (4, "Software and Tools"),
                            (5, "Missions and Instruments"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "division",
                    models.IntegerField(
                        choices=[
                            (1, "Astrophysics"),
                            (2, "Biological and Physical Sciences"),
                            (3, "Earth Science"),
                            (4, "Heliophysics"),
                            (5, "Planetary Science"),
                            (6, "General"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_urls",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["url"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeltaUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(unique=True, verbose_name="Url")),
                ("scraped_title", models.CharField(blank=True, default="", verbose_name="Scraped Title")),
                ("generated_title", models.CharField(blank=True, default="", verbose_name="Generated Title")),
                ("visited", models.BooleanField(default=False)),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (1, "Images"),
                            (2, "Data"),
                            (3, "Documentation"),
                            (4, "Software and Tools"),
                            (5, "Missions and Instruments"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "division",
                    models.IntegerField(
                        choices=[
                            (1, "Astrophysics"),
                            (2, "Biological and Physical Sciences"),
                            (3, "Earth Science"),
                            (4, "Heliophysics"),
                            (5, "Planetary Science"),
                            (6, "General"),
                        ],
                        null=True,
                    ),
                ),
                ("delete", models.BooleanField(default=False)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_urls",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["url"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CuratedUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(unique=True, verbose_name="Url")),
                ("scraped_title", models.CharField(blank=True, default="", verbose_name="Scraped Title")),
                ("generated_title", models.CharField(blank=True, default="", verbose_name="Generated Title")),
                ("visited", models.BooleanField(default=False)),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (1, "Images"),
                            (2, "Data"),
                            (3, "Documentation"),
                            (4, "Software and Tools"),
                            (5, "Missions and Instruments"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "division",
                    models.IntegerField(
                        choices=[
                            (1, "Astrophysics"),
                            (2, "Biological and Physical Sciences"),
                            (3, "Earth Science"),
                            (4, "Heliophysics"),
                            (5, "Planetary Science"),
                            (6, "General"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_urls",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["url"],
                "abstract": False,
            },
        ),
    ]
