# Generated by Django 4.2.9 on 2024-11-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0060_alter_candidateurl_scraped_text"),
        ("sde_collections", "0062_deltatitlepattern_deltaresolvedtitleerror_and_more"),
    ]

    operations = []
