# Generated by Django 4.2.9 on 2024-11-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0063_merge_20241112_1428"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curatedurl",
            options={"ordering": ["url"], "verbose_name": "Curated Urls", "verbose_name_plural": "Curated Urls"},
        ),
        migrations.AlterModelOptions(
            name="deltadivisionpattern",
            options={"verbose_name": "Delta Division Pattern", "verbose_name_plural": "Delta Division Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltadocumenttypepattern",
            options={
                "verbose_name": "Delta Document Type Pattern",
                "verbose_name_plural": "Delta Document Type Patterns",
            },
        ),
        migrations.AlterModelOptions(
            name="deltaexcludepattern",
            options={"verbose_name": "Delta Exclude Pattern", "verbose_name_plural": "Delta Exclude Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltaincludepattern",
            options={"verbose_name": "Delta Include Pattern", "verbose_name_plural": "Delta Include Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltatitlepattern",
            options={"verbose_name": "Delta Title Pattern", "verbose_name_plural": "Delta Title Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltaurl",
            options={"ordering": ["url"], "verbose_name": "Delta Urls", "verbose_name_plural": "Delta Urls"},
        ),
        migrations.AlterModelOptions(
            name="dumpurl",
            options={"ordering": ["url"], "verbose_name": "Dump Urls", "verbose_name_plural": "Dump Urls"},
        ),
        migrations.AddField(
            model_name="curatedurl",
            name="scraped_text",
            field=models.TextField(
                blank=True, default="", help_text="This is the text scraped by Sinequa", verbose_name="Scraped Text"
            ),
        ),
        migrations.AddField(
            model_name="deltaurl",
            name="scraped_text",
            field=models.TextField(
                blank=True, default="", help_text="This is the text scraped by Sinequa", verbose_name="Scraped Text"
            ),
        ),
        migrations.AddField(
            model_name="dumpurl",
            name="scraped_text",
            field=models.TextField(
                blank=True, default="", help_text="This is the text scraped by Sinequa", verbose_name="Scraped Text"
            ),
        ),
        migrations.AlterField(
            model_name="curatedurl",
            name="generated_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title generated based on a Title Pattern",
                verbose_name="Generated Title",
            ),
        ),
        migrations.AlterField(
            model_name="curatedurl",
            name="scraped_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the original title scraped by Sinequa",
                verbose_name="Scraped Title",
            ),
        ),
        migrations.AlterField(
            model_name="deltaurl",
            name="generated_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title generated based on a Title Pattern",
                verbose_name="Generated Title",
            ),
        ),
        migrations.AlterField(
            model_name="deltaurl",
            name="scraped_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the original title scraped by Sinequa",
                verbose_name="Scraped Title",
            ),
        ),
        migrations.AlterField(
            model_name="dumpurl",
            name="generated_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the title generated based on a Title Pattern",
                verbose_name="Generated Title",
            ),
        ),
        migrations.AlterField(
            model_name="dumpurl",
            name="scraped_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This is the original title scraped by Sinequa",
                verbose_name="Scraped Title",
            ),
        ),
    ]
