# Generated by Django 4.2.9 on 2024-11-23 17:44

from django.db import migrations, models
import sde_collections.models.delta_patterns


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0065_rename_delete_deltaurl_to_delete_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deltadivisionpattern",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="deltadocumenttypepattern",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="deltaexcludepattern",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="deltaincludepattern",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="deltatitlepattern",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="deltadivisionpattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all documents in the collection",
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="deltadocumenttypepattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all documents in the collection",
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="deltaexcludepattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all documents in the collection",
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="deltaincludepattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all documents in the collection",
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="deltatitlepattern",
            name="match_pattern",
            field=models.CharField(
                help_text="This pattern is compared against the URL of all documents in the collection",
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="deltatitlepattern",
            name="title_pattern",
            field=models.CharField(
                help_text="Pattern for the new title. Support exact replacement or sinequa-valid code",
                validators=[sde_collections.models.delta_patterns.validate_title_pattern],
                verbose_name="Title Pattern",
            ),
        ),
    ]
