# Generated by Django 4.2.9 on 2024-11-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0059_candidateurl_tdamm_tag_manual_and_more"),
        ("sde_collections", "0065_rename_delete_deltaurl_to_delete_and_more"),
    ]

    operations = []
