# Generated by Django 4.2.9 on 2024-11-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0066_merge_20241120_0158"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateurl",
            name="tdamm_tag_manual",
        ),
        migrations.RemoveField(
            model_name="candidateurl",
            name="tdamm_tag_ml",
        ),
    ]
