# Generated by Django 4.2.9 on 2024-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0066_alter_deltadivisionpattern_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deltadivisionpattern",
            options={
                "ordering": ["match_pattern"],
                "verbose_name": "Delta Division Pattern",
                "verbose_name_plural": "Delta Division Patterns",
            },
        ),
        migrations.AlterModelOptions(
            name="deltadocumenttypepattern",
            options={
                "ordering": ["match_pattern"],
                "verbose_name": "Delta Document Type Pattern",
                "verbose_name_plural": "Delta Document Type Patterns",
            },
        ),
        migrations.AlterModelOptions(
            name="deltaexcludepattern",
            options={
                "ordering": ["match_pattern"],
                "verbose_name": "Delta Exclude Pattern",
                "verbose_name_plural": "Delta Exclude Patterns",
            },
        ),
        migrations.AlterModelOptions(
            name="deltaincludepattern",
            options={
                "ordering": ["match_pattern"],
                "verbose_name": "Delta Include Pattern",
                "verbose_name_plural": "Delta Include Patterns",
            },
        ),
        migrations.AlterModelOptions(
            name="deltatitlepattern",
            options={
                "ordering": ["match_pattern"],
                "verbose_name": "Delta Title Pattern",
                "verbose_name_plural": "Delta Title Patterns",
            },
        ),
        migrations.AlterUniqueTogether(
            name="deltadivisionpattern",
            unique_together={("collection", "match_pattern")},
        ),
        migrations.AlterUniqueTogether(
            name="deltadocumenttypepattern",
            unique_together={("collection", "match_pattern")},
        ),
        migrations.AlterUniqueTogether(
            name="deltaexcludepattern",
            unique_together={("collection", "match_pattern")},
        ),
        migrations.AlterUniqueTogether(
            name="deltaincludepattern",
            unique_together={("collection", "match_pattern")},
        ),
        migrations.AlterUniqueTogether(
            name="deltatitlepattern",
            unique_together={("collection", "match_pattern")},
        ),
    ]
