# Generated by Django 4.2.9 on 2024-11-24 19:39

from django.db import migrations, models
import django.db.models.deletion
import sde_collections.models.delta_patterns


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0067_alter_deltadivisionpattern_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deltadivisionpattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="deltadivisionpattern",
            name="curated_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.curatedurl"),
        ),
        migrations.AlterField(
            model_name="deltadivisionpattern",
            name="delta_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.deltaurl"),
        ),
        migrations.AlterField(
            model_name="deltadocumenttypepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="deltadocumenttypepattern",
            name="curated_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.curatedurl"),
        ),
        migrations.AlterField(
            model_name="deltadocumenttypepattern",
            name="delta_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.deltaurl"),
        ),
        migrations.AlterField(
            model_name="deltaexcludepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="deltaexcludepattern",
            name="curated_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.curatedurl"),
        ),
        migrations.AlterField(
            model_name="deltaexcludepattern",
            name="delta_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.deltaurl"),
        ),
        migrations.AlterField(
            model_name="deltaincludepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="deltaincludepattern",
            name="curated_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.curatedurl"),
        ),
        migrations.AlterField(
            model_name="deltaincludepattern",
            name="delta_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.deltaurl"),
        ),
        migrations.AlterField(
            model_name="deltatitlepattern",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)ss",
                to="sde_collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="deltatitlepattern",
            name="curated_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.curatedurl"),
        ),
        migrations.AlterField(
            model_name="deltatitlepattern",
            name="delta_urls",
            field=models.ManyToManyField(related_name="%(class)ss", to="sde_collections.deltaurl"),
        ),
        migrations.AlterField(
            model_name="deltatitlepattern",
            name="title_pattern",
            field=models.CharField(
                help_text="Pattern for the new title. Can be an exact replacement string or sinequa-valid code",
                validators=[sde_collections.models.delta_patterns.validate_title_pattern],
                verbose_name="Title Pattern",
            ),
        ),
    ]
