# Generated by Django 4.2.9 on 2024-12-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0068_alter_deltadivisionpattern_collection_and_more"),
        ("sde_collections", "0069_candidateurl_tdamm_tag_manual_and_more"),
    ]

    operations = []
