# Generated by Django 4.2.9 on 2024-12-06 03:51
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_initial_reindexing_status(apps, schema_editor):
    Collection = apps.get_model("sde_collections", "Collection")

    # Define the workflow status values
    RESEARCH_IN_PROGRESS = 1
    READY_FOR_ENGINEERING = 2
    ENGINEERING_IN_PROGRESS = 3
    READY_FOR_CURATION = 4
    CURATION_IN_PROGRESS = 5
    CURATED = 6
    QUALITY_FIXED = 7
    SECRET_DEPLOYMENT_STARTED = 8
    SECRET_DEPLOYMENT_FAILED = 9
    READY_FOR_LRM_QUALITY_CHECK = 10
    READY_FOR_FINAL_QUALITY_CHECK = 11
    QUALITY_CHECK_FAILED = 12
    QUALITY_CHECK_PERFECT = 13
    MERGE_PENDING = 14
    NEEDS_DELETE = 19

    # Workflow statuses that should be marked as reindexing not needed
    reindexing_not_needed_statuses = [
        RESEARCH_IN_PROGRESS,
        READY_FOR_ENGINEERING,
        ENGINEERING_IN_PROGRESS,
        READY_FOR_CURATION,
        CURATION_IN_PROGRESS,
        CURATED,
        QUALITY_FIXED,
        SECRET_DEPLOYMENT_STARTED,
        SECRET_DEPLOYMENT_FAILED,
        READY_FOR_LRM_QUALITY_CHECK,
        READY_FOR_FINAL_QUALITY_CHECK,
        QUALITY_CHECK_FAILED,
        QUALITY_CHECK_PERFECT,
        MERGE_PENDING,
        NEEDS_DELETE,
    ]

    # Set collections that don't need reindexing
    Collection.objects.filter(workflow_status__in=reindexing_not_needed_statuses).update(
        reindexing_status=1
    )  # NOT_NEEDED

    # All other collections need reindexing
    Collection.objects.exclude(workflow_status__in=reindexing_not_needed_statuses).update(reindexing_status=2)  # NEEDED


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sde_collections", "0071_alter_candidateurl_tdamm_tag_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="reindexing_status",
            field=models.IntegerField(
                choices=[
                    (1, "Reindexing Not Needed"),
                    (2, "Reindexing Needed on LRM Dev"),
                    (3, "Reindexing Finished on LRM Dev"),
                    (4, "Ready for Curation"),
                    (5, "Curated"),
                    (6, "Indexed on Prod"),
                ],
                default=1,
                verbose_name="Reindexing Status",
            ),
        ),
        migrations.CreateModel(
            name="ReindexingHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reindexing_status",
                    models.IntegerField(
                        choices=[
                            (1, "Reindexing Not Needed"),
                            (2, "Reindexing Needed on LRM Dev"),
                            (3, "Reindexing Finished on LRM Dev"),
                            (4, "Ready for Curation"),
                            (5, "Curated"),
                            (6, "Indexed on Prod"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "old_status",
                    models.IntegerField(
                        choices=[
                            (1, "Reindexing Not Needed"),
                            (2, "Reindexing Needed on LRM Dev"),
                            (3, "Reindexing Finished on LRM Dev"),
                            (4, "Ready for Curation"),
                            (5, "Curated"),
                            (6, "Indexed on Prod"),
                        ],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reindexing_history",
                        to="sde_collections.collection",
                    ),
                ),
                (
                    "curated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(set_initial_reindexing_status),
    ]
