# Generated by Django 4.2.9 on 2024-12-06 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sde_collections", "0071_alter_candidateurl_tdamm_tag_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="reindexing_status",
            field=models.IntegerField(
                choices=[
                    (1, "Reindexing Not Needed"),
                    (2, "Reindexing Needed on LRM Dev"),
                    (3, "Reindexing Finished on LRM Dev"),
                    (4, "Ready for Curation"),
                    (5, "Curated"),
                    (6, "Indexed on Prod"),
                ],
                default=1,
                verbose_name="Reindexing Status",
            ),
        ),
        migrations.CreateModel(
            name="ReindexingHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reindexing_status",
                    models.IntegerField(
                        choices=[
                            (1, "Reindexing Not Needed"),
                            (2, "Reindexing Needed on LRM Dev"),
                            (3, "Reindexing Finished on LRM Dev"),
                            (4, "Ready for Curation"),
                            (5, "Curated"),
                            (6, "Indexed on Prod"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "old_status",
                    models.IntegerField(
                        choices=[
                            (1, "Reindexing Not Needed"),
                            (2, "Reindexing Needed on LRM Dev"),
                            (3, "Reindexing Finished on LRM Dev"),
                            (4, "Ready for Curation"),
                            (5, "Curated"),
                            (6, "Indexed on Prod"),
                        ],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reindexing_history",
                        to="sde_collections.collection",
                    ),
                ),
                (
                    "curated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
