# Generated by Django 4.2.9 on 2024-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0072_collection_reindexing_status_reindexinghistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="workflow_status",
            field=models.IntegerField(
                choices=[
                    (1, "Research in Progress"),
                    (2, "Ready for Engineering"),
                    (3, "Engineering in Progress"),
                    (4, "Ready for Curation"),
                    (5, "Curation in Progress"),
                    (6, "Curated"),
                    (7, "Quality Fixed"),
                    (8, "Secret Deployment Started"),
                    (9, "Secret Deployment Failed"),
                    (10, "Ready for LRM Quality Check"),
                    (11, "Ready for Quality Check"),
                    (12, "QC: Failed"),
                    (18, "QC: Minor Issues"),
                    (13, "QC: Perfect"),
                    (14, "Prod: Perfect"),
                    (15, "Prod: Minor Issues"),
                    (16, "Prod: Major Issues"),
                    (17, "Code Merge Pending"),
                    (19, "Delete from Prod"),
                    (20, "Indexing Finished on LRM Dev"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="workflowhistory",
            name="old_status",
            field=models.IntegerField(
                choices=[
                    (1, "Research in Progress"),
                    (2, "Ready for Engineering"),
                    (3, "Engineering in Progress"),
                    (4, "Ready for Curation"),
                    (5, "Curation in Progress"),
                    (6, "Curated"),
                    (7, "Quality Fixed"),
                    (8, "Secret Deployment Started"),
                    (9, "Secret Deployment Failed"),
                    (10, "Ready for LRM Quality Check"),
                    (11, "Ready for Quality Check"),
                    (12, "QC: Failed"),
                    (18, "QC: Minor Issues"),
                    (13, "QC: Perfect"),
                    (14, "Prod: Perfect"),
                    (15, "Prod: Minor Issues"),
                    (16, "Prod: Major Issues"),
                    (17, "Code Merge Pending"),
                    (19, "Delete from Prod"),
                    (20, "Indexing Finished on LRM Dev"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflowhistory",
            name="workflow_status",
            field=models.IntegerField(
                choices=[
                    (1, "Research in Progress"),
                    (2, "Ready for Engineering"),
                    (3, "Engineering in Progress"),
                    (4, "Ready for Curation"),
                    (5, "Curation in Progress"),
                    (6, "Curated"),
                    (7, "Quality Fixed"),
                    (8, "Secret Deployment Started"),
                    (9, "Secret Deployment Failed"),
                    (10, "Ready for LRM Quality Check"),
                    (11, "Ready for Quality Check"),
                    (12, "QC: Failed"),
                    (18, "QC: Minor Issues"),
                    (13, "QC: Perfect"),
                    (14, "Prod: Perfect"),
                    (15, "Prod: Minor Issues"),
                    (16, "Prod: Major Issues"),
                    (17, "Code Merge Pending"),
                    (19, "Delete from Prod"),
                    (20, "Indexing Finished on LRM Dev"),
                ],
                default=1,
            ),
        ),
    ]
