# Generated by Django 4.2.9 on 2024-12-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0073_alter_collection_workflow_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="reindexing_status",
            field=models.IntegerField(
                choices=[
                    (1, "Re-Indexing Not Needed"),
                    (2, "Re-Indexing Needed"),
                    (3, "Re-Indexing Finished"),
                    (4, "Ready for Re-Curation"),
                    (5, "Re-Curation Finished"),
                    (6, "Re-Indexed on Prod"),
                ],
                default=1,
                verbose_name="Reindexing Status",
            ),
        ),
        migrations.AlterField(
            model_name="reindexinghistory",
            name="old_status",
            field=models.IntegerField(
                choices=[
                    (1, "Re-Indexing Not Needed"),
                    (2, "Re-Indexing Needed"),
                    (3, "Re-Indexing Finished"),
                    (4, "Ready for Re-Curation"),
                    (5, "Re-Curation Finished"),
                    (6, "Re-Indexed on Prod"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reindexinghistory",
            name="reindexing_status",
            field=models.IntegerField(
                choices=[
                    (1, "Re-Indexing Not Needed"),
                    (2, "Re-Indexing Needed"),
                    (3, "Re-Indexing Finished"),
                    (4, "Ready for Re-Curation"),
                    (5, "Re-Curation Finished"),
                    (6, "Re-Indexed on Prod"),
                ],
                default=1,
            ),
        ),
    ]
