# Generated by Django 4.2.9 on 2024-12-13 19:57

from django.db import migrations, models


def migrate_reindexing_statuses(apps, schema_editor):
    Collection = apps.get_model("sde_collections", "Collection")
    ReindexingHistory = apps.get_model("sde_collections", "ReindexingHistory")

    # Update Collections
    Collection.objects.filter(reindexing_status=6).update(reindexing_status=7)  # Move "Indexed on Prod" first
    Collection.objects.filter(reindexing_status=5).update(reindexing_status=6)  # Then move "Curated"
    # 5 is now free for "Curation in Progress"

    # Update ReindexingHistory
    ReindexingHistory.objects.filter(reindexing_status=6).update(reindexing_status=7)
    ReindexingHistory.objects.filter(reindexing_status=5).update(reindexing_status=6)

    ReindexingHistory.objects.filter(old_status=6).update(old_status=7)
    ReindexingHistory.objects.filter(old_status=5).update(old_status=6)


def reverse_migrate_reindexing_statuses(apps, schema_editor):
    Collection = apps.get_model("sde_collections", "Collection")
    ReindexingHistory = apps.get_model("sde_collections", "ReindexingHistory")

    # Reverse Collections
    Collection.objects.filter(reindexing_status=5).update(reindexing_status=None)  # Clear new status
    Collection.objects.filter(reindexing_status=6).update(reindexing_status=5)
    Collection.objects.filter(reindexing_status=7).update(reindexing_status=6)

    # Reverse ReindexingHistory
    ReindexingHistory.objects.filter(reindexing_status=5).update(reindexing_status=None)
    ReindexingHistory.objects.filter(reindexing_status=6).update(reindexing_status=5)
    ReindexingHistory.objects.filter(reindexing_status=7).update(reindexing_status=6)

    ReindexingHistory.objects.filter(old_status=5).update(old_status=None)
    ReindexingHistory.objects.filter(old_status=6).update(old_status=5)
    ReindexingHistory.objects.filter(old_status=7).update(old_status=6)


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0074_alter_collection_reindexing_status_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_reindexing_statuses, reverse_migrate_reindexing_statuses),
        migrations.AlterField(
            model_name="collection",
            name="reindexing_status",
            field=models.IntegerField(
                choices=[
                    (1, "Re-Indexing Not Needed"),
                    (2, "Re-Indexing Needed"),
                    (3, "Re-Indexing Finished"),
                    (4, "Ready for Re-Curation"),
                    (5, "Re-Curation in Progress"),
                    (6, "Re-Curation Finished"),
                    (7, "Re-Indexed on Prod"),
                ],
                default=1,
                verbose_name="Reindexing Status",
            ),
        ),
        migrations.AlterField(
            model_name="reindexinghistory",
            name="old_status",
            field=models.IntegerField(
                choices=[
                    (1, "Re-Indexing Not Needed"),
                    (2, "Re-Indexing Needed"),
                    (3, "Re-Indexing Finished"),
                    (4, "Ready for Re-Curation"),
                    (5, "Re-Curation in Progress"),
                    (6, "Re-Curation Finished"),
                    (7, "Re-Indexed on Prod"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reindexinghistory",
            name="reindexing_status",
            field=models.IntegerField(
                choices=[
                    (1, "Re-Indexing Not Needed"),
                    (2, "Re-Indexing Needed"),
                    (3, "Re-Indexing Finished"),
                    (4, "Ready for Re-Curation"),
                    (5, "Re-Curation in Progress"),
                    (6, "Re-Curation Finished"),
                    (7, "Re-Indexed on Prod"),
                ],
                default=1,
            ),
        ),
    ]
