# Generated by Django 4.2.9 on 2025-01-09 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sde_collections", "0075_alter_collection_reindexing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="reindexing_curated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reindexing_curated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
