# Generated by Django 4.2.9 on 2025-02-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0075_alter_collection_reindexing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deltaresolvedtitle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="deltaresolvedtitleerror",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="deltaresolvedtitle",
            index=models.Index(fields=["status", "created_at"], name="sde_collect_status_42dc80_idx"),
        ),
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
