# Generated by Django 4.2.9 on 2025-02-14 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0075_alter_collection_reindexing_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeltaTdammTagPattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "match_pattern",
                    models.CharField(
                        help_text="This pattern is compared against the URL of all documents in the collection",
                        verbose_name="Pattern",
                    ),
                ),
                (
                    "match_pattern_type",
                    models.IntegerField(choices=[(1, "Individual URL Pattern"), (2, "Multi-URL Pattern")], default=1),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("Not TDAMM", "Not TDAMM"),
                            ("MMA_M_EM", "Messenger - EM Radiation"),
                            ("MMA_M_EM_G", "Messenger - EM Radiation - Gamma rays"),
                            ("MMA_M_EM_X", "Messenger - EM Radiation - X-rays"),
                            ("MMA_M_EM_U", "Messenger - EM Radiation - Ultraviolet"),
                            ("MMA_M_EM_O", "Messenger - EM Radiation - Optical"),
                            ("MMA_M_EM_I", "Messenger - EM Radiation - Infrared"),
                            ("MMA_M_EM_M", "Messenger - EM Radiation - Microwave"),
                            ("MMA_M_EM_R", "Messenger - EM Radiation - Radio"),
                            ("MMA_M_G", "Messenger - Gravitational Waves"),
                            ("MMA_M_G_CBI", "Messenger - Gravitational Waves - Compact Binary Inspiral"),
                            ("MMA_M_G_S", "Messenger - Gravitational Waves - Stochastic"),
                            ("MMA_M_G_CON", "Messenger - Gravitational Waves - Continuous"),
                            ("MMA_M_G_B", "Messenger - Gravitational Waves - Burst"),
                            ("MMA_M_C", "Messenger - Cosmic Rays"),
                            ("MMA_M_N", "Messenger - Neutrinos"),
                            ("MMA_O_BI", "Objects - Binaries"),
                            ("MMA_O_BI_BBH", "Objects - Binaries - Binary Black Holes"),
                            ("MMA_O_BI_BNS", "Objects - Binaries - Binary Neutron Stars"),
                            ("MMA_O_BI_C", "Objects - Binaries - Cataclysmic Variables"),
                            ("MMA_O_BI_N", "Objects - Binaries - Neutron Star-Black Hole"),
                            ("MMA_O_BI_B", "Objects - Binaries - Binary Pulsars"),
                            ("MMA_O_BI_W", "Objects - Binaries - White Dwarf Binaries"),
                            ("MMA_O_BH", "Objects - Black Holes"),
                            ("MMA_O_BH_AGN", "Objects - Black Holes - Active Galactic Nuclei"),
                            ("MMA_O_BH_IM", "Objects - Black Holes - Intermediate mass"),
                            ("MMA_O_BH_STM", "Objects - Black Holes - Stellar mass"),
                            ("MMA_O_BH_SUM", "Objects - Black Holes - Supermassive"),
                            ("MMA_O_E", "Objects - Exoplanets"),
                            ("MMA_O_N", "Objects - Neutron Stars"),
                            ("MMA_O_N_M", "Objects - Neutron Stars - Magnetars"),
                            ("MMA_O_N_P", "Objects - Neutron Stars - Pulsars"),
                            ("MMA_O_N_PWN", "Objects - Neutron Stars - Pulsar Wind Nebula"),
                            ("MMA_O_S", "Objects - Supernova Remnants"),
                            ("MMA_S_F", "Signals - Fast Radio Bursts"),
                            ("MMA_S_G", "Signals - Gamma-ray Bursts"),
                            ("MMA_S_K", "Signals - Kilonovae"),
                            ("MMA_S_N", "Signals - Novae"),
                            ("MMA_S_P", "Signals - Pevatrons"),
                            ("MMA_S_ST", "Signals - Stellar flares"),
                            ("MMA_S_SU", "Signals - Supernovae"),
                        ],
                        help_text="TDAMM tag to apply",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("ml", "Machine Learning")], default="manual", max_length=10
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)ss",
                        to="sde_collections.collection",
                    ),
                ),
                ("curated_urls", models.ManyToManyField(related_name="%(class)ss", to="sde_collections.curatedurl")),
                ("delta_urls", models.ManyToManyField(related_name="%(class)ss", to="sde_collections.deltaurl")),
            ],
            options={
                "verbose_name": "Delta TDAMM Tag Pattern",
                "verbose_name_plural": "Delta TDAMM Tag Patterns",
                "ordering": ["match_pattern"],
                "abstract": False,
                "unique_together": {("collection", "match_pattern")},
            },
        ),
    ]
