# Generated by Django 4.2.9 on 2025-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0076_deltaresolvedtitle_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
