# Generated by Django 4.2.9 on 2025-01-29 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sde_collections", "0077_alter_collection_reindexing_curated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="reindexinghistory",
            name="old_curator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="old_curator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
