# Generated by Django 4.2.9 on 2025-02-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0077_remove_deltatdammtagpattern_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deltatdammtagpattern",
            name="source",
            field=models.CharField(default="manual", max_length=10),
        ),
    ]
