# Generated by Django 4.2.9 on 2025-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0078_alter_deltaresolvedtitle_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deltaresolvedtitle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
