# Generated by Django 4.2.9 on 2025-02-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0078_deltatdammtagpattern_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deltatdammtagpattern",
            unique_together={("collection", "match_pattern", "tag", "operation", "source")},
        ),
    ]
