# Generated by Django 4.2.9 on 2026-08-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0078_alter_collection_workflow_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperConfigOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_pages", models.PositiveIntegerField(blank=True, help_text="Crawler cap: 100,000", null=True)),
                ("depth_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "delay",
                    models.FloatField(
                        blank=True, help_text="Seconds between requests (crawler default 0.25)", null=True
                    ),
                ),
                ("concurrent_requests", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("obey_robots", models.BooleanField(blank=True, null=True)),
                ("include_subdomains", models.BooleanField(blank=True, null=True)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraper_config",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraper Config Override",
            },
        ),
        migrations.CreateModel(
            name="ScrapeDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                ("ssm_command_id", models.CharField(max_length=64)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_dispatches",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Scrape Dispatches",
                "ordering": ["-dispatched_at"],
            },
        ),
    ]
