# Generated by Django 4.2.9 on 2026-08-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0079_scraperconfigoverride_scrapedispatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(max_length=64)),
                ("target", models.CharField(choices=[("test", "test"), ("prod", "prod")], max_length=8)),
                ("task_arn", models.CharField(blank=True, default="", max_length=256)),
                ("previous_workflow_status", models.IntegerField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_dispatches",
                        to="sde_collections.collection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Index Dispatches",
                "ordering": ["-dispatched_at"],
            },
        ),
    ]
