# Generated by Django 4.2.9 on 2025-04-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0077_alter_candidateurl_tdamm_tag_manual_and_more"),
        ("sde_collections", "0081_alter_deltatdammtagpattern_tags"),
    ]

    operations = []
