# this list is read by generate_scrapers when making a list of sources to scrape
test_sources = [
    {"source_name": "quotes", "url": "https://quotes.toscrape.com"},
]

turned_on_sources = [
    "algorithm_theoretical_basis_documents",
    "eos_mission_page",
    "gcn_circulars",
    "gcn_missions_instruments_and_facilities",
    "general_coordinates_network_gcn",
    "giss_software_tools",
    "our_changing_planet_the_view_from_space_images",
    "GENELAB_METADATA_Website",
    "PDS_EPIC_Model_Website",
    "NasaEarthObservationWebsite",
    "PDS_PDS4_Training_Documents_Website",
    "GENELAB_Github_DataProcessing",
    "PDS_Notebook_Website",
    "PDS_Metadata_Injector_for_PDS_Labels_Website",
    "PDS_Photojournal_Website",
    "PDS_ODE_REST_Service_Website",
    "PDS_Lunar_Orbiter_Data_Explorer_Website",
    "PDS_NASA_Science_Solar_System_Exploration_Website",
    "PDS_Messenger_MASCS_UVVS_Archive_Page_Website",
    "PDS_Image_Atlas_Website",
    "PDS_NASAs_Eyes_Website",
    "ASTRO_James_Webb_Space_Telescope_Website",
    "SPEDAS_Website",
    "CCMC_Website",
    "ASTRO_Data_Hosted_on_LAMBDA_Website",
    "PDS_Toolkits_Website",
    "ASTRO_Hubble_Source_Catalog_Search_API_Website",
    "PyHC_Website",
    "PDS_Java_Mission-planning_and_Analysis_for_Remote_Sensing_(JMARS)_Website",
    "ASTRO_HEASARC_Software_Website",
    "PDS_NASA_Science_Earths_Moon_Website",
    "Helio_Events_Knowledgebase_Website",
    "DataPathFinder",
    "NTRS",
    "PDS_Juno_Archive_Page_Website",
    "PDS_Astropedia_Lunar_and_Planetary_Cartographic_Catalog_Website",
    "PDS_Odyssey_GRS_Data_Node_Website",
    "SPASE_Website",
    "PDS_Astromat_Astromaterials_Data_System_Website",
    "PDS_Small_Bodies_Image_Browser_Website",
    "PDS_Virtual_Astronaut_Website",
    "PDS_Pluto_and_Arrokoth_Data_Archive_Website",
    "PDS_Users_Guides_Website",
    "PDS_Mars_Orbiter_Data_Website",
    "PDS_Mars_Exploration_Program_Website",
    "PDS_Mercury_Data_Archive_Website",
    "PDS_TES_Data_Node_Website",
    "PDS_Jupiter_Data_Archive_Website",
    "GENELAB_Github_SampleProcessing",
    "PDS_PDS_Annex_Products_Website",
    "PDS_PDS_Tool_Registry_Website",
    "PDS_SBN_Tools_Utilities_and_Interfaces_Website",
    "PDS_ISIS_Astro_Website",
    "PDS_Missions_Website",
    "GENELAB_Publications_Website",
    "PDS_DIVINER_RDR_Query_Website",
    "ASTRO_NASA_Exoplanet_Archive_Documents_Website",
    "ASTRO_API_Search_Website",
    "PDS_High-Resolution_Transmission_Molecular_Absorption_Database_(HITRAN)_Website",
    "PDS_Analyst_Notebook_Website",
    "ASTRO_ZMAST_API_Website",
    "ASTRO_MAST_Documentation_Website",
    "PDS_Data_Pilot_Website",
    "PDS_PDS_Software_Tools_Tutorial_and_Viewers_Website",
    "PDS_Gravity_Models_Website",
    "PDS_Venus_Archive_Page_Website",
    "Autoplot_Website",
    "PDS_Rings_Website",
    "PDS_Mission_Data_Archive_Website",
    "PDS_LOLA_RDR_Query_Website",
    "PDS_PPI_Software_Website",
    "PDS_ISIS_Website",
    "PDS_USGS_Pilot_Website",
    "PDS_Imaging_Software_Website",
    "PDS_Missions_Archive_Page_Website",
    "PDS_SPICE_Archives_Website",
    "PDS_LOLA_RDR_Query_V20_Website",
    "PDS_Subscription_Service_Website",
    "ASTRO_Calibration_Documentation_Website",
    "PDS_Venus_Orbital_Data_Explorer_Website",
    "PDS_SPICE_Programming_Lessons_Website",
    "PDS_API_Legacy_All",
    "ASTRO_Data_Reduction_Tools_Website",
    "Helioviewer_Website",
    "ASTRO_HIRES_PRV_Website",
    "PDS_PDS4_Documents_Website",
    "ASTRO_Image_Cutouts_Website",
    "PDS_Ring-Moon_Systems_Node_On-line_Tools_Website",
    "PDS_Neptune_Archive_Page_Website",
    "PDS_Uranus_Data_Archive_Website",
    "PDS_Mars_Lander_Data_Website",
    "PDS_Lunar_Atmospheres_Data_Archive_Website",
    "GENELAB_Github_Training",
    "ASTRO_TAP_Search_Website",
    "PDS_Mercury_Orbital_Data_Explorer_Website",
    "CMR_API",
    "PDS_Outer_Planets_Icy_Satellites_Archive_Page_Website",
    "ARSETAppliedSciences",
    "PDS_Planetary_Science_Tools_Website",
    "PDS_SPICE_Utility_and_Application_Programs_Website",
    "PDS_Geosciences_Node_Spectral_Library_Website",
    "PDS_SPICE_Toolkit_Website",
    "PDS_NASA_Solar_System_Treks_Website",
    "PDS_PDS_Documentation_Website",
    "PDS_Geosciences_Data_Holdings_Website",
    "PDS_SPICE-enhanced_Cosmographia_Website",
    "ASTRO_Contributed_Datasets_Website",
    "PDS_PDS3_Standards_Reference_Website",
    "PDS_PDS4_Local_Data_Dictionary_Tool_Website",
    "PDS_Saturn_Data_Archive_Website",
    "PDS_DIVINER_RDR_Query_V20_Website",
    "ASTRO_exoMAST_API_Website",
    "ASTRO_Spitzer_Tools_Website",
    "PDS_Data_Volumes_Index_Website",
    "HAPI_Website",
    "PDS_PDS4_JParser_Website",
    "PDS_Solar_System_Exploration_Research_Virtual_Institute_(SSERVI)_Website",
    "PDS_MRO_Coordinated_Observation_Website",
    "PDS_Mars_Orbital_Data_Explorer_Website",
    "PDS_Titan_Data_Archive_Website",
    "PDS_Atmospheric_Escape_Chemistry_Page_Website",
    "PDS_Collision_Induced_Absorption_Model_Website",
    "ASTRO_NAVO_HEASARC",
    "CASEI_Campaign",
    "CASEI_Deployment",
    "CASEI_Instrument",
    "CASEI_Platform",
    "giss_datasets_and_derived_materials",
    "giss_publication_list",
    "nasa_global_climate_change",
    "goddard_institute_for_space_studies",
    "earth_observer_publications",
    "our_changing_planet_the_view_from_space_images",
    "nasa_sea_level_change",
    "nasa_carbon_monitoring_system",
    "emac_exoplanet_modeling_and_analysis_center",
    "algorithm_theoretical_basis_documents",
    "emac_exoplanet_modeling_and_analysis_center",
    "PDS_SPICE_Tutorials_Website",
]

kaylins_new_sources = [
    {"source_name": "nasa_power", "url": "https://power.larc.nasa.gov/"},
    {
        "source_name": "emac_exoplanet_modeling_and_analysis_center",
        "url": "https://emac.gsfc.nasa.gov/",
    },
    {
        "source_name": "goddard_institute_for_space_studies",
        "url": "https://www.giss.nasa.gov/",
    },
    {
        "source_name": "earth_science_decadal_surveys",
        "url": "https://science.nasa.gov/earth-science/decadal-surveys/",
    },
    {
        "source_name": "exoplanet_opacities_database",
        "url": "https://science.data.nasa.gov/opacities/",
    },
    {
        "source_name": "interactive_multiinstrument_database_of_solar_flares",
        "url": "https://data.nas.nasa.gov/helio/portals/solarflares/",
    },
    {"source_name": "general_coordinates_network_gcn", "url": "https://gcn.nasa.gov/"},
    {
        "source_name": "gcn_missions_instruments_and_facilities",
        "url": "https://gcn.nasa.gov/missions",
    },
    {"source_name": "gcn_circulars", "url": "https://gcn.nasa.gov/circulars"},
    {
        "source_name": "igwn_public_alerts_user_guide",
        "url": "https://emfollow.docs.ligo.org/userguide/",
    },
    {
        "source_name": "algorithm_theoretical_basis_documents",
        "url": "https://eospso.nasa.gov/content/algorithm-theoretical-basis-documents",
    },
    {
        "source_name": "eos_mission_page",
        "url": "https://eospso.nasa.gov/content/all-missions",
    },
    {
        "source_name": "earth_observer_publications",
        "url": "https://eospso.nasa.gov/earth-observer-archive/",
    },
    {
        "source_name": "our_changing_planet_the_view_from_space_images",
        "url": "https://eospso.nasa.gov/content/our-changing-planet-view-space",
    },
    {"source_name": "nasa_global_climate_change", "url": "https://climate.nasa.gov/"},
    {"source_name": "giss_publication_list", "url": "https://pubs.giss.nasa.gov/"},
    {"source_name": "giss_software_tools", "url": "https://www.giss.nasa.gov/tools/"},
    {
        "source_name": "giss_datasets_and_derived_materials",
        "url": "https://data.giss.nasa.gov/",
    },
    {
        "source_name": "nasa_wavelength",
        "url": "https://science.nasa.gov/learners/wavelength",
    },
    {"source_name": "my_nasa_data", "url": "https://mynasadata.larc.nasa.gov/"},
    {
        "source_name": "mars_target_encyclopeida_mte",
        "url": "https://github.com/wkiri/MTE",
    },
    {
        "source_name": "astrogeology_analysis_ready_data",
        "url": "https://stac.astrogeology.usgs.gov/docs/",
    },
    {
        "source_name": "nasa_science_missions_earth",
        "url": "https://science.nasa.gov/missions-page?field_division_tid=103&field_phase_tid=All",
    },
    {"source_name": "f_prime", "url": "https://github.com/nasa/fprime"},
    {"source_name": "nasa_sea_level_change", "url": "https://sealevel.nasa.gov/"},
    {"source_name": "earth_observing_dashboard", "url": "https://eodashboard.org/"},
    {
        "source_name": "fire_information_for_resource_management_system_firms",
        "url": "https://firms.modaps.eosdis.nasa.gov/",
    },
    {"source_name": "nasa_carbon_monitoring_system", "url": "https://carbon.nasa.gov/"},
    {
        "source_name": "nasa_2023_climate_strategy",
        "url": "https://www.nasa.gov/sites/default/files/atoms/files/advancing_nasas_climate_strategy_2023.pdf",
    },
]
# i've started running up through igwn
sprint_2_sources = [
    {
        "source_name": "nasa_science_solar_system_exploration",
        "url": "https://solarsystem.nasa.gov/",
    },
    {
        "source_name": "emac_exoplanet_modeling_and_analysis_center",
        "url": "https://emac.gsfc.nasa.gov/",
    },
    {"source_name": "mars_exploration_program", "url": "https://mars.nasa.gov/"},
    {
        "source_name": "astropedia_lunar_and_planetary_cartographic_catalog",
        "url": "https://astrogeology.usgs.gov/search?pmi-target=mercury",
    },
    {
        "source_name": "pds_cassini_resource_page_website",
        "url": "https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/Cassini/Cassini.html",
    },
    {
        "source_name": "goddard_institute_for_space_studies",
        "url": "https://www.giss.nasa.gov/",
    },
    {
        "source_name": "missions_archive_page",
        "url": "https://pds-ppi.igpp.ucla.edu/mission",
    },
    {
        "source_name": "pds_pds_small_bodies_node_asteroid_dust_subnode_website",
        "url": "https://sbn.psi.edu/pds/",
    },
    {
        "source_name": "earth_science_decadal_surveys",
        "url": "https://science.nasa.gov/earth-science/decadal-surveys/",
    },
    {
        "source_name": "exoplanet_opacities_database",
        "url": "https://science.data.nasa.gov/opacities/",
    },
    {"source_name": "nasa_power", "url": "https://power.larc.nasa.gov/"},
    {
        "source_name": "our_changing_planet_the_view_from_space_images",
        "url": "https://eospso.nasa.gov/content/our-changing-planet-view-space",
    },
    {
        "source_name": "igwn_public_alerts_user_guide",
        "url": "https://emfollow.docs.ligo.org/userguide/",
    },
    {"source_name": "nasa_global_climate_change", "url": "https://climate.nasa.gov/"},
    {
        "source_name": "recently_archived_volumes",
        "url": "https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/recent.htm",
    },
    {"source_name": "lsda_website", "url": "https://nlsp.nasa.gov/explore/lsdahome"},
    {
        "source_name": "small_bodies_data_ferret",
        "url": "https://sbnapps.psi.edu/ferret/listDatasets.action",
    },
    {
        "source_name": "pds_data_archive_website",
        "url": "https://pds-imaging.jpl.nasa.gov/data/",
    },
    {
        "source_name": "interactive_multiinstrument_database_of_solar_flares",
        "url": "https://data.nas.nasa.gov/helio/portals/solarflares/",
    },
    {"source_name": "general_coordinates_network_gcn", "url": "https://gcn.nasa.gov/"},
    {
        "source_name": "gcn_missions_instruments_and_facilities",
        "url": "https://gcn.nasa.gov/missions",
    },
    {
        "source_name": "heliophysics_events_knowledgebase",
        "url": "https://www.lmsal.com/hek/",
    },
    {
        "source_name": "planetary_plasma_interactions_data_volumes",
        "url": "https://pds-ppi.igpp.ucla.edu/search/?s=*",
    },
    {
        "source_name": "astromaterials_acquisition_and_curation_office",
        "url": "https://curator.jsc.nasa.gov/",
    },
    {
        "source_name": "nasa_wavelength",
        "url": "https://science.nasa.gov/learners/wavelength",
    },
    {"source_name": "nasa_sea_level_change", "url": "https://sealevel.nasa.gov/"},
]

finished_sources = [
    "algorithm_theoretical_basis_documents",
    "astrogeology_analysis_ready_data",
    "astromaterials_acquisition_and_curation_office",
    "astropedia_lunar_and_planetary_cartographic_catalog",
    "earth_observing_dashboard",
    "earth_science_decadal_surveys",
    "emac_exoplanet_modeling_and_analysis_center",
    "eos_mission_page",
    "exoplanet_opacities_database",
    "fire_information_for_resource_management_system_firms",
    "f_prime",
    "gcn_circulars",
    "gcn_missions_instruments_and_facilities",
    "general_coordinates_network_gcn",
    "giss_datasets_and_derived_materials",
    "giss_publication_list",
    "giss_software_tools",
    "goddard_institute_for_space_studies",
    "heliophysics_events_knowledgebase",
    "igwn_public_alerts_user_guide",
    "nasa_science_earths_moon",
    "pds4_documents",
    "pds_near_earth_asteroid_rendezvous_near_data_archive_website",
    "solar_system_exploration_research_virtual_institute_sservi",
    "SPASE_JSON_List",
]

sprint_3_sources = [
    {
        "source_name": "solar_system_exploration_research_virtual_institute_sservi",
        "url": "https://sservi.nasa.gov/",
    },
    {
        "source_name": "mars_gcm",
        "url": "https://pds-atmospheres.nmsu.edu/PDS/data/mogc_0001",
    },
    {"source_name": "pds_archive_navigator_website", "url": "https://arcnav.psi.edu/"},
    {
        "source_name": "pds_near_earth_asteroid_rendezvous_near_data_archive_website",
        "url": "https://arcnav.psi.edu/urn:nasa:pds:context:investigation:mission.near_earth_asteroid_rendezvous",
    },
    {"source_name": "my_nasa_data", "url": "https://mynasadata.larc.nasa.gov/"},
    {"source_name": "mars_target_encyclopedia", "url": "https://github.com/wkiri/MTE"},
    {
        "source_name": "astrogeology_analysis_ready_data",
        "url": "https://stac.astrogeology.usgs.gov/docs/",
    },
    {"source_name": "heasarc", "url": "https://heasarc.gsfc.nasa.gov/"},
    {"source_name": "nasa_science_earths_moon", "url": "https://moon.nasa.gov/"},
    {
        "source_name": "pds4_documents",
        "url": "https://pds.nasa.gov/datastandards/documents/",
    },
    {"source_name": "code_nasa_api", "url": "https://impact.earthdata.nasa.gov/casei/"},
    {"source_name": "nasa_earth_observations", "url": "https://neo.gsfc.nasa.gov/"},
    {
        "source_name": "nasa_science_missions_earth",
        "url": "https://science.nasa.gov/missions-page?field_division_tid=103&field_phase_tid=All",
    },
    {"source_name": "f_prime", "url": "https://github.com/nasa/fprime"},
    {"source_name": "ceos_missions", "url": "https://mims.nasa-impact.net/docs"},
    {
        "source_name": "caldb_documentation",
        "url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/caldb_doc.html",
    },
    {
        "source_name": "genelab_metadata_api",
        "url": "https://genelab.nasa.gov/genelabAPIs#metadata",
    },
    {
        "source_name": "generic_kernels",
        "url": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/",
    },
    {"source_name": "casei", "url": "https://impact.earthdata.nasa.gov/casei/"},
    {"source_name": "errata", "url": "https://pds-ppi.igpp.ucla.edu/search/?e="},
    {"source_name": "ceos_instruments", "url": "https://mims.nasa-impact.net/docs"},
    {"source_name": "james_webb_space_telescope", "url": "https://webb.nasa.gov/"},
    {
        "source_name": "casei_instruments",
        "url": "https://admg.nasa-impact.net/api/docs/",
    },
    {
        "source_name": "highenergy_missions",
        "url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/alphabet.html",
    },
    {
        "source_name": "arset_applied_sciences",
        "url": "https://appliedsciences.nasa.gov/join-mission/training",
    },
    {
        "source_name": "casei_deployments",
        "url": "https://admg.nasa-impact.net/api/docs/",
    },
    {
        "source_name": "operational_flightother_project_kernels",
        "url": "https://naif.jpl.nasa.gov/naif/data_operational.html",
    },
    {
        "source_name": "spice_programming_lessons",
        "url": "https://naif.jpl.nasa.gov/naif/lessons.html",
    },
    {
        "source_name": "spice_selftraining",
        "url": "https://naif.jpl.nasa.gov/naif/self_training.html",
    },
    {
        "source_name": "spice_toolkit_documentation",
        "url": "https://naif.jpl.nasa.gov/naif/documentation.html",
    },
    {
        "source_name": "spice_tutorials",
        "url": "https://naif.jpl.nasa.gov/naif/tutorials.html",
    },
    {
        "source_name": "mast_documentation",
        "url": "https://outerspace.stsci.edu/display/MASTDOCS/Portal+Guidel",
    },
    {"source_name": "ccmc", "url": "https://ccmc.gsfc.nasa.gov/"},
    {"source_name": "nasa_carbon_monitoring_system", "url": "https://carbon.nasa.gov/"},
    {
        "source_name": "nasa_2023_climate_strategy",
        "url": "https://www.nasa.gov/sites/default/files/atoms/files/advancing_nasas_climate_strategy_2023.pdf",
    },
    {"source_name": "nasa_sea_level_change", "url": "https://sealevel.nasa.gov/"},
    {"source_name": "earth_observing_dashboard", "url": "https://eodashboard.org/"},
    {"source_name": "earth_observing_dashboard", "url": "https://eodashboard.org/"},
    {
        "source_name": "fire_information_for_resource_management_system_firms",
        "url": "https://firms.modaps.eosdis.nasa.gov/",
    },
]

# scraped on test server with the new title code
# TODO: are all of these actually showing?
already_scraped_sources = [
    "ASTRO_Missions_and_Data_Website",
    "CODE_NASA_API",
    "NasaEarthObservationWebsite",
    "DataPathFinder",
    "ASTRO_James_Webb_Space_Telescope_Website",
    "ASTRO_High-Energy_Missions_Website",
    "ARSETAppliedSciences",
    "GENELAB_Publications_Website",
]


all_sources = kaylins_new_sources + sprint_2_sources + sprint_3_sources
remaining_sources = [s for s in all_sources if s["source_name"] not in finished_sources]
