# this list is read by generate_scrapers when making a list of sources to scrape
test_sources = [
    {"source_name": "quotes", "url": "https://quotes.toscrape.com"},
]

turned_on_sources = [
    "algorithm_theoretical_basis_documents",
    "eos_mission_page",
    "gcn_circulars",
    "gcn_missions_instruments_and_facilities",
    "general_coordinates_network_gcn",
    "giss_software_tools",
    "our_changing_planet_the_view_from_space_images",
    "GENELAB_METADATA_Website",
    "PDS_EPIC_Model_Website",
    "NasaEarthObservationWebsite",
    "PDS_PDS4_Training_Documents_Website",
    "GENELAB_Github_DataProcessing",
    "PDS_Notebook_Website",
    "PDS_Metadata_Injector_for_PDS_Labels_Website",
    "PDS_Photojournal_Website",
    "PDS_ODE_REST_Service_Website",
    "PDS_Lunar_Orbiter_Data_Explorer_Website",
    "PDS_NASA_Science_Solar_System_Exploration_Website",
    "PDS_Messenger_MASCS_UVVS_Archive_Page_Website",
    "PDS_Image_Atlas_Website",
    "PDS_NASAs_Eyes_Website",
    "ASTRO_James_Webb_Space_Telescope_Website",
    "SPEDAS_Website",
    "CCMC_Website",
    "ASTRO_Data_Hosted_on_LAMBDA_Website",
    "PDS_Toolkits_Website",
    "ASTRO_Hubble_Source_Catalog_Search_API_Website",
    "PyHC_Website",
    "PDS_Java_Mission-planning_and_Analysis_for_Remote_Sensing_(JMARS)_Website",
    "ASTRO_HEASARC_Software_Website",
    "PDS_NASA_Science_Earths_Moon_Website",
    "Helio_Events_Knowledgebase_Website",
    "DataPathFinder",
    "NTRS",
    "PDS_Juno_Archive_Page_Website",
    "PDS_Astropedia_Lunar_and_Planetary_Cartographic_Catalog_Website",
    "PDS_Odyssey_GRS_Data_Node_Website",
    "SPASE_Website",
    "PDS_Astromat_Astromaterials_Data_System_Website",
    "PDS_Small_Bodies_Image_Browser_Website",
    "PDS_Virtual_Astronaut_Website",
    "PDS_Pluto_and_Arrokoth_Data_Archive_Website",
    "PDS_Users_Guides_Website",
    "PDS_Mars_Orbiter_Data_Website",
    "PDS_Mars_Exploration_Program_Website",
    "PDS_Mercury_Data_Archive_Website",
    "PDS_TES_Data_Node_Website",
    "PDS_Jupiter_Data_Archive_Website",
    "GENELAB_Github_SampleProcessing",
    "PDS_PDS_Annex_Products_Website",
    "PDS_PDS_Tool_Registry_Website",
    "PDS_SBN_Tools_Utilities_and_Interfaces_Website",
    "PDS_ISIS_Astro_Website",
    "PDS_Missions_Website",
    "GENELAB_Publications_Website",
    "PDS_DIVINER_RDR_Query_Website",
    "ASTRO_NASA_Exoplanet_Archive_Documents_Website",
    "ASTRO_API_Search_Website",
    "PDS_High-Resolution_Transmission_Molecular_Absorption_Database_(HITRAN)_Website",
    "PDS_Analyst_Notebook_Website",
    "ASTRO_ZMAST_API_Website",
    "ASTRO_MAST_Documentation_Website",
    "PDS_Data_Pilot_Website",
    "PDS_PDS_Software_Tools_Tutorial_and_Viewers_Website",
    "PDS_Gravity_Models_Website",
    "PDS_Venus_Archive_Page_Website",
    "Autoplot_Website",
    "PDS_Rings_Website",
    "PDS_Mission_Data_Archive_Website",
    "PDS_LOLA_RDR_Query_Website",
    "PDS_PPI_Software_Website",
    "PDS_ISIS_Website",
    "PDS_USGS_Pilot_Website",
    "PDS_Imaging_Software_Website",
    "PDS_Missions_Archive_Page_Website",
    "PDS_SPICE_Archives_Website",
    "PDS_LOLA_RDR_Query_V20_Website",
    "PDS_Subscription_Service_Website",
    "ASTRO_Calibration_Documentation_Website",
    "PDS_Venus_Orbital_Data_Explorer_Website",
    "PDS_SPICE_Programming_Lessons_Website",
    "PDS_API_Legacy_All",
    "ASTRO_Data_Reduction_Tools_Website",
    "Helioviewer_Website",
    "ASTRO_HIRES_PRV_Website",
    "PDS_PDS4_Documents_Website",
    "ASTRO_Image_Cutouts_Website",
    "PDS_Ring-Moon_Systems_Node_On-line_Tools_Website",
    "PDS_Neptune_Archive_Page_Website",
    "PDS_Uranus_Data_Archive_Website",
    "PDS_Mars_Lander_Data_Website",
    "PDS_Lunar_Atmospheres_Data_Archive_Website",
    "GENELAB_Github_Training",
    "ASTRO_TAP_Search_Website",
    "PDS_Mercury_Orbital_Data_Explorer_Website",
    "CMR_API",
    "PDS_Outer_Planets_Icy_Satellites_Archive_Page_Website",
    "ARSETAppliedSciences",
    "PDS_Planetary_Science_Tools_Website",
    "PDS_SPICE_Utility_and_Application_Programs_Website",
    "PDS_Geosciences_Node_Spectral_Library_Website",
    "PDS_SPICE_Toolkit_Website",
    "PDS_NASA_Solar_System_Treks_Website",
    "PDS_PDS_Documentation_Website",
    "PDS_Geosciences_Data_Holdings_Website",
    "PDS_SPICE-enhanced_Cosmographia_Website",
    "ASTRO_Contributed_Datasets_Website",
    "PDS_PDS3_Standards_Reference_Website",
    "PDS_PDS4_Local_Data_Dictionary_Tool_Website",
    "PDS_Saturn_Data_Archive_Website",
    "PDS_DIVINER_RDR_Query_V20_Website",
    "ASTRO_exoMAST_API_Website",
    "ASTRO_Spitzer_Tools_Website",
    "PDS_Data_Volumes_Index_Website",
    "HAPI_Website",
    "PDS_PDS4_JParser_Website",
    "PDS_Solar_System_Exploration_Research_Virtual_Institute_(SSERVI)_Website",
    "PDS_MRO_Coordinated_Observation_Website",
    "PDS_Mars_Orbital_Data_Explorer_Website",
    "PDS_Titan_Data_Archive_Website",
    "PDS_Atmospheric_Escape_Chemistry_Page_Website",
    "PDS_Collision_Induced_Absorption_Model_Website",
    "ASTRO_NAVO_HEASARC",
    "CASEI_Campaign",
    "CASEI_Deployment",
    "CASEI_Instrument",
    "CASEI_Platform",
    "giss_datasets_and_derived_materials",
    "giss_publication_list",
    "nasa_global_climate_change",
    "goddard_institute_for_space_studies",
    "earth_observer_publications",
    "our_changing_planet_the_view_from_space_images",
    "nasa_sea_level_change",
    "nasa_carbon_monitoring_system",
    "emac_exoplanet_modeling_and_analysis_center",
    "algorithm_theoretical_basis_documents",
    "emac_exoplanet_modeling_and_analysis_center",
    "PDS_SPICE_Tutorials_Website",
]

kaylins_new_sources = [
    {"source_name": "nasa_power", "url": "https://power.larc.nasa.gov/"},
    {
        "source_name": "emac_exoplanet_modeling_and_analysis_center",
        "url": "https://emac.gsfc.nasa.gov/",
    },
    {
        "source_name": "goddard_institute_for_space_studies",
        "url": "https://www.giss.nasa.gov/",
    },
    {
        "source_name": "earth_science_decadal_surveys",
        "url": "https://science.nasa.gov/earth-science/decadal-surveys/",
    },
    {
        "source_name": "exoplanet_opacities_database",
        "url": "https://science.data.nasa.gov/opacities/",
    },
    {
        "source_name": "interactive_multiinstrument_database_of_solar_flares",
        "url": "https://data.nas.nasa.gov/helio/portals/solarflares/",
    },
    {"source_name": "general_coordinates_network_gcn", "url": "https://gcn.nasa.gov/"},
    {
        "source_name": "gcn_missions_instruments_and_facilities",
        "url": "https://gcn.nasa.gov/missions",
    },
    {"source_name": "gcn_circulars", "url": "https://gcn.nasa.gov/circulars"},
    {
        "source_name": "igwn_public_alerts_user_guide",
        "url": "https://emfollow.docs.ligo.org/userguide/",
    },
    {
        "source_name": "algorithm_theoretical_basis_documents",
        "url": "https://eospso.nasa.gov/content/algorithm-theoretical-basis-documents",
    },
    {
        "source_name": "eos_mission_page",
        "url": "https://eospso.nasa.gov/content/all-missions",
    },
    {
        "source_name": "earth_observer_publications",
        "url": "https://eospso.nasa.gov/earth-observer-archive/",
    },
    {
        "source_name": "our_changing_planet_the_view_from_space_images",
        "url": "https://eospso.nasa.gov/content/our-changing-planet-view-space",
    },
    {"source_name": "nasa_global_climate_change", "url": "https://climate.nasa.gov/"},
    {"source_name": "giss_publication_list", "url": "https://pubs.giss.nasa.gov/"},
    {"source_name": "giss_software_tools", "url": "https://www.giss.nasa.gov/tools/"},
    {
        "source_name": "giss_datasets_and_derived_materials",
        "url": "https://data.giss.nasa.gov/",
    },
    {
        "source_name": "nasa_wavelength",
        "url": "https://science.nasa.gov/learners/wavelength",
    },
    {"source_name": "my_nasa_data", "url": "https://mynasadata.larc.nasa.gov/"},
    {
        "source_name": "mars_target_encyclopeida_mte",
        "url": "https://github.com/wkiri/MTE",
    },
    {
        "source_name": "astrogeology_analysis_ready_data",
        "url": "https://stac.astrogeology.usgs.gov/docs/",
    },
    {
        "source_name": "nasa_science_missions_earth",
        "url": "https://science.nasa.gov/missions-page?field_division_tid=103&field_phase_tid=All",
    },
    {"source_name": "f_prime", "url": "https://github.com/nasa/fprime"},
    {"source_name": "nasa_sea_level_change", "url": "https://sealevel.nasa.gov/"},
    {"source_name": "earth_observing_dashboard", "url": "https://eodashboard.org/"},
    {
        "source_name": "fire_information_for_resource_management_system_firms",
        "url": "https://firms.modaps.eosdis.nasa.gov/",
    },
    {"source_name": "nasa_carbon_monitoring_system", "url": "https://carbon.nasa.gov/"},
    {
        "source_name": "nasa_2023_climate_strategy",
        "url": "https://www.nasa.gov/sites/default/files/atoms/files/advancing_nasas_climate_strategy_2023.pdf",
    },
]
# i've started running up through igwn
sprint_2_sources = [
    {
        "source_name": "nasa_science_solar_system_exploration",
        "url": "https://solarsystem.nasa.gov/",
    },
    {
        "source_name": "emac_exoplanet_modeling_and_analysis_center",
        "url": "https://emac.gsfc.nasa.gov/",
    },
    {"source_name": "mars_exploration_program", "url": "https://mars.nasa.gov/"},
    {
        "source_name": "astropedia_lunar_and_planetary_cartographic_catalog",
        "url": "https://astrogeology.usgs.gov/search?pmi-target=mercury",
    },
    {
        "source_name": "pds_cassini_resource_page_website",
        "url": "https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/Cassini/Cassini.html",
    },
    {
        "source_name": "goddard_institute_for_space_studies",
        "url": "https://www.giss.nasa.gov/",
    },
    {
        "source_name": "missions_archive_page",
        "url": "https://pds-ppi.igpp.ucla.edu/mission",
    },
    {
        "source_name": "pds_pds_small_bodies_node_asteroid_dust_subnode_website",
        "url": "https://sbn.psi.edu/pds/",
    },
    {
        "source_name": "earth_science_decadal_surveys",
        "url": "https://science.nasa.gov/earth-science/decadal-surveys/",
    },
    {
        "source_name": "exoplanet_opacities_database",
        "url": "https://science.data.nasa.gov/opacities/",
    },
    {"source_name": "nasa_power", "url": "https://power.larc.nasa.gov/"},
    {
        "source_name": "our_changing_planet_the_view_from_space_images",
        "url": "https://eospso.nasa.gov/content/our-changing-planet-view-space",
    },
    {
        "source_name": "igwn_public_alerts_user_guide",
        "url": "https://emfollow.docs.ligo.org/userguide/",
    },
    {"source_name": "nasa_global_climate_change", "url": "https://climate.nasa.gov/"},
    {
        "source_name": "recently_archived_volumes",
        "url": "https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/recent.htm",
    },
    {"source_name": "lsda_website", "url": "https://nlsp.nasa.gov/explore/lsdahome"},
    {
        "source_name": "small_bodies_data_ferret",
        "url": "https://sbnapps.psi.edu/ferret/listDatasets.action",
    },
    {
        "source_name": "pds_data_archive_website",
        "url": "https://pds-imaging.jpl.nasa.gov/data/",
    },
    {
        "source_name": "interactive_multiinstrument_database_of_solar_flares",
        "url": "https://data.nas.nasa.gov/helio/portals/solarflares/",
    },
    {"source_name": "general_coordinates_network_gcn", "url": "https://gcn.nasa.gov/"},
    {
        "source_name": "gcn_missions_instruments_and_facilities",
        "url": "https://gcn.nasa.gov/missions",
    },
    {
        "source_name": "heliophysics_events_knowledgebase",
        "url": "https://www.lmsal.com/hek/",
    },
    {
        "source_name": "planetary_plasma_interactions_data_volumes",
        "url": "https://pds-ppi.igpp.ucla.edu/search/?s=*",
    },
    {
        "source_name": "astromaterials_acquisition_and_curation_office",
        "url": "https://curator.jsc.nasa.gov/",
    },
    {
        "source_name": "nasa_wavelength",
        "url": "https://science.nasa.gov/learners/wavelength",
    },
    {"source_name": "nasa_sea_level_change", "url": "https://sealevel.nasa.gov/"},
]

finished_sources = [
    "algorithm_theoretical_basis_documents",
    "astrogeology_analysis_ready_data",
    "astromaterials_acquisition_and_curation_office",
    "astropedia_lunar_and_planetary_cartographic_catalog",
    "earth_observing_dashboard",
    "earth_science_decadal_surveys",
    "emac_exoplanet_modeling_and_analysis_center",
    "eos_mission_page",
    "exoplanet_opacities_database",
    "fire_information_for_resource_management_system_firms",
    "f_prime",
    "gcn_circulars",
    "gcn_missions_instruments_and_facilities",
    "general_coordinates_network_gcn",
    "giss_datasets_and_derived_materials",
    "giss_publication_list",
    "giss_software_tools",
    "goddard_institute_for_space_studies",
    "heliophysics_events_knowledgebase",
    "igwn_public_alerts_user_guide",
    "nasa_science_earths_moon",
    "pds4_documents",
    "pds_near_earth_asteroid_rendezvous_near_data_archive_website",
    "solar_system_exploration_research_virtual_institute_sservi",
    "SPASE_JSON_List",
]

sprint_3_sources = [
    {
        "source_name": "solar_system_exploration_research_virtual_institute_sservi",
        "url": "https://sservi.nasa.gov/",
    },
    {
        "source_name": "mars_gcm",
        "url": "https://pds-atmospheres.nmsu.edu/PDS/data/mogc_0001",
    },
    {"source_name": "pds_archive_navigator_website", "url": "https://arcnav.psi.edu/"},
    {
        "source_name": "pds_near_earth_asteroid_rendezvous_near_data_archive_website",
        "url": "https://arcnav.psi.edu/urn:nasa:pds:context:investigation:mission.near_earth_asteroid_rendezvous",
    },
    {"source_name": "my_nasa_data", "url": "https://mynasadata.larc.nasa.gov/"},
    {"source_name": "mars_target_encyclopedia", "url": "https://github.com/wkiri/MTE"},
    {
        "source_name": "astrogeology_analysis_ready_data",
        "url": "https://stac.astrogeology.usgs.gov/docs/",
    },
    {"source_name": "heasarc", "url": "https://heasarc.gsfc.nasa.gov/"},
    {"source_name": "nasa_science_earths_moon", "url": "https://moon.nasa.gov/"},
    {
        "source_name": "pds4_documents",
        "url": "https://pds.nasa.gov/datastandards/documents/",
    },
    {"source_name": "code_nasa_api", "url": "https://impact.earthdata.nasa.gov/casei/"},
    {"source_name": "nasa_earth_observations", "url": "https://neo.gsfc.nasa.gov/"},
    {
        "source_name": "nasa_science_missions_earth",
        "url": "https://science.nasa.gov/missions-page?field_division_tid=103&field_phase_tid=All",
    },
    {"source_name": "f_prime", "url": "https://github.com/nasa/fprime"},
    {"source_name": "ceos_missions", "url": "https://mims.nasa-impact.net/docs"},
    {
        "source_name": "caldb_documentation",
        "url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/caldb_doc.html",
    },
    {
        "source_name": "genelab_metadata_api",
        "url": "https://genelab.nasa.gov/genelabAPIs#metadata",
    },
    {
        "source_name": "generic_kernels",
        "url": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/",
    },
    {"source_name": "casei", "url": "https://impact.earthdata.nasa.gov/casei/"},
    {"source_name": "errata", "url": "https://pds-ppi.igpp.ucla.edu/search/?e="},
    {"source_name": "ceos_instruments", "url": "https://mims.nasa-impact.net/docs"},
    {"source_name": "james_webb_space_telescope", "url": "https://webb.nasa.gov/"},
    {
        "source_name": "casei_instruments",
        "url": "https://admg.nasa-impact.net/api/docs/",
    },
    {
        "source_name": "highenergy_missions",
        "url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/alphabet.html",
    },
    {
        "source_name": "arset_applied_sciences",
        "url": "https://appliedsciences.nasa.gov/join-mission/training",
    },
    {
        "source_name": "casei_deployments",
        "url": "https://admg.nasa-impact.net/api/docs/",
    },
    {
        "source_name": "operational_flightother_project_kernels",
        "url": "https://naif.jpl.nasa.gov/naif/data_operational.html",
    },
    {
        "source_name": "spice_programming_lessons",
        "url": "https://naif.jpl.nasa.gov/naif/lessons.html",
    },
    {
        "source_name": "spice_selftraining",
        "url": "https://naif.jpl.nasa.gov/naif/self_training.html",
    },
    {
        "source_name": "spice_toolkit_documentation",
        "url": "https://naif.jpl.nasa.gov/naif/documentation.html",
    },
    {
        "source_name": "spice_tutorials",
        "url": "https://naif.jpl.nasa.gov/naif/tutorials.html",
    },
    {
        "source_name": "mast_documentation",
        "url": "https://outerspace.stsci.edu/display/MASTDOCS/Portal+Guidel",
    },
    {"source_name": "ccmc", "url": "https://ccmc.gsfc.nasa.gov/"},
    {"source_name": "nasa_carbon_monitoring_system", "url": "https://carbon.nasa.gov/"},
    {
        "source_name": "nasa_2023_climate_strategy",
        "url": "https://www.nasa.gov/sites/default/files/atoms/files/advancing_nasas_climate_strategy_2023.pdf",
    },
    {"source_name": "nasa_sea_level_change", "url": "https://sealevel.nasa.gov/"},
    {"source_name": "earth_observing_dashboard", "url": "https://eodashboard.org/"},
    {"source_name": "earth_observing_dashboard", "url": "https://eodashboard.org/"},
    {
        "source_name": "fire_information_for_resource_management_system_firms",
        "url": "https://firms.modaps.eosdis.nasa.gov/",
    },
]

# scraped on test server with the new title code
# TODO: are all of these actually showing?
already_scraped_sources = [
    "ASTRO_Missions_and_Data_Website",
    "CODE_NASA_API",
    "NasaEarthObservationWebsite",
    "DataPathFinder",
    "ASTRO_James_Webb_Space_Telescope_Website",
    "ASTRO_High-Energy_Missions_Website",
    "ARSETAppliedSciences",
    "GENELAB_Publications_Website",
]

# emily put together a list of sources which were previously limited but we now
# want more than the top page:
# https://docs.google.com/spreadsheets/d/1U95xEseibgoHmTSyT6akPxuMVRIUeEu2vOyu9i8teb4/edit#gid=0
# however, many of these need special attention, so this list in this variable isn't complete
remove_top_limitation_sources = [
    "Autoplot_Website",
    "PyHC_Website",
    "SPEDAS_Website",
    "ASTRO_Hubble_Source_Catalog_Search_API_Website",
    "PDS_PDS_Tool_Registry_Website",
]

lis_new_sources = [
    "algorithm_theoretical_basis_documents",
    "eos_mission_page",
    "gcn_circulars",
    "gcn_missions_instruments_and_facilities",
    "general_coordinates_network_gcn",
    "giss_software_tools",
    "our_changing_planet_the_view_from_space_images",
]

all_sources = kaylins_new_sources + sprint_2_sources + sprint_3_sources
remaining_sources = [s for s in all_sources if s["source_name"] not in finished_sources]


sources_with_documents_20230605 = [
    "algorithm_theoretical_basis_documents",
    "ARSETAppliedSciences",
    "ASTRO_API_Search_Website",
    "ASTRO_Calibration_Documentation_Website",
    "ASTRO_Contributed_Datasets_Website",
    "ASTRO_Data_Reduction_Tools_Website",
    "ASTRO_exoMAST_API_Website",
    "ASTRO_HEASARC_Software_Website",
    "ASTRO_HIRES_PRV_Website",
    "ASTRO_Hubble_Source_Catalog_Search_API_Website",
    "ASTRO_Image_Cutouts_Website",
    "ASTRO_James_Webb_Space_Telescope_Website",
    "ASTRO_MAST_Documentation_Website",
    "ASTRO_NASA_Exoplanet_Archive_Documents_Website",
    "ASTRO_NAVO_HEASARC",
    "ASTRO_Spitzer_Tools_Website",
    "ASTRO_TAP_Search_Website",
    "ASTRO_ZMAST_API_Website",
    "astrogeology_analysis_ready_data",
    "CASEI_Campaign",
    "CASEI_Deployment",
    "CASEI_Instrument",
    "CASEI_Platform",
    "CMR_API",
    "DataPathFinder",
    "earth_observer_publications",
    "earth_observing_dashboard",
    "earth_science_decadal_surveys",
    "eos_mission_page",
    "f_prime",
    "fire_information_for_resource_management_system_firms",
    "gcn_circulars",
    "gcn_missions_instruments_and_facilities",
    "GENELAB_Github_DataProcessing",
    "GENELAB_Github_SampleProcessing",
    "GENELAB_Github_Training",
    "GENELAB_METADATA_Website",
    "GENELAB_Publications_Website",
    "general_coordinates_network_gcn",
    "giss_datasets_and_derived_materials",
    "giss_publication_list",
    "giss_software_tools",
    "goddard_institute_for_space_studies",
    "interactive_multiinstrument_database_of_solar_flares",
    "mars_target_encyclopedia_mte",
    "my_nasa_data",
    "nasa_2023_climate_strategy",
    "nasa_carbon_monitoring_system",
    "nasa_global_climate_change",
    "nasa_sea_level_change",
    "NasaEarthObservationWebsite",
    "our_changing_planet_the_view_from_space_images",
    "PDS_Analyst_Notebook_Website",
    "PDS_API_Legacy_All",
    "PDS_Astromat_Astromaterials_Data_System_Website",
    "PDS_Astropedia_Lunar_and_Planetary_Cartographic_Catalog_Website",
    "PDS_Atmospheric_Escape_Chemistry_Page_Website",
    "PDS_Collision_Induced_Absorption_Model_Website",
    "PDS_Data_Pilot_Website",
    "PDS_Data_Volumes_Index_Website",
    "PDS_DIVINER_RDR_Query_V20_Website",
    "PDS_DIVINER_RDR_Query_Website",
    "PDS_EPIC_Model_Website",
    "PDS_Geosciences_Data_Holdings_Website",
    "PDS_Geosciences_Node_Spectral_Library_Website",
    "PDS_Gravity_Models_Website",
    "PDS_High-Resolution_Transmission_Molecular_Absorption_Database_(HITRAN)_Website",
    "PDS_Image_Atlas_Website",
    "PDS_Imaging_Software_Website",
    "PDS_ISIS_Astro_Website",
    "PDS_ISIS_Website",
    "PDS_Java_Mission-planning_and_Analysis_for_Remote_Sensing_(JMARS)_Website",
    "PDS_Juno_Archive_Page_Website",
    "PDS_Jupiter_Data_Archive_Website",
    "PDS_LOLA_RDR_Query_V20_Website",
    "PDS_LOLA_RDR_Query_Website",
    "PDS_Lunar_Atmospheres_Data_Archive_Website",
    "PDS_Lunar_Orbiter_Data_Explorer_Website",
    "PDS_Mars_Exploration_Program_Website",
    "PDS_Mars_Lander_Data_Website",
    "PDS_Mars_Orbital_Data_Explorer_Website",
    "PDS_Mars_Orbiter_Data_Website",
    "PDS_Mercury_Data_Archive_Website",
    "PDS_Mercury_Orbital_Data_Explorer_Website",
    "PDS_Messenger_MASCS_UVVS_Archive_Page_Website",
    "PDS_Metadata_Injector_for_PDS_Labels_Website",
    "PDS_Missions_Archive_Page_Website",
    "PDS_MRO_Coordinated_Observation_Website",
    "PDS_NASA_Science_Earths_Moon_Website",
    "PDS_NASA_Science_Solar_System_Exploration_Website",
    "PDS_NASAs_Eyes_Website",
    "PDS_Neptune_Archive_Page_Website",
    "PDS_Notebook_Website",
    "PDS_Operational_Flight_Other_Project_Kernels_Website",
    "PDS_Outer_Planets_Icy_Satellites_Archive_Page_Website",
    "PDS_PDS3_Standards_Reference_Website",
    "PDS_PDS4_Documents_Website",
    "PDS_PDS4_JParser_Website",
    "PDS_PDS4_Local_Data_Dictionary_Tool_Website",
    "PDS_PDS4_Training_Documents_Website",
    "PDS_PDS_Annex_Products_Website",
    "PDS_PDS_Documentation_Website",
    "PDS_PDS_Software_Tools_Tutorial_and_Viewers_Website",
    "PDS_PDS_Tool_Registry_Website",
    "PDS_Photojournal_Website",
    "PDS_Planetary_Science_Tools_Website",
    "PDS_Pluto_and_Arrokoth_Data_Archive_Website",
    "PDS_PPI_Software_Website",
    "PDS_Ring-Moon_Systems_Node_On-line_Tools_Website",
    "PDS_Rings_Website",
    "PDS_Saturn_Data_Archive_Website",
    "PDS_SBN_Tools_Utilities_and_Interfaces_Website",
    "PDS_Small_Bodies_Image_Browser_Website",
    "PDS_Solar_System_Exploration_Research_Virtual_Institute_(SSERVI)_Website",
    "PDS_SPICE-enhanced_Cosmographia_Website",
    "PDS_SPICE_Archives_Website",
    "PDS_SPICE_Programming_Lessons_Website",
    "PDS_SPICE_Toolkit_Website",
    "PDS_SPICE_Tutorials_Website",
    "PDS_SPICE_Utility_and_Application_Programs_Website",
    "PDS_Subscription_Service_Website",
    "PDS_TES_Data_Node_Website",
    "PDS_Titan_Data_Archive_Website",
    "PDS_Toolkits_Website",
    "PDS_Uranus_Data_Archive_Website",
    "PDS_Users_Guides_Website",
    "PDS_USGS_Pilot_Website",
    "PDS_Venus_Archive_Page_Website",
    "PDS_Venus_Orbital_Data_Explorer_Website",
    "PDS_Virtual_Astronaut_Website",
]


created_from_scratch = [
    "archived_synthetic_data",
    "astroquery_api_search_mast_queries",
    "co_plotter",
    "contributed_datasets_in_the_exoplanet_archive",
    "coordinate_calculator",
    "corot_exoplanet_archive_etss_data_sets",
    "exo_mast",
    "exoplanet_atmosphere_observability_table",
    "extinction_calculator",
    "heasarc_browse_batch_interface",
    "heasarc_download_scripts",
    "high_level_science_products",
    "hubble_source_catalog_search",
    "ipac_table_validator",
    "koa_program_friendly_image_access_service",
    "lbti_archive",
    "mast",
    "mast_api_search",
    "mast_hubble_search",
    "mast_portal",
    "mast_query_casjobs",
    "mast_web_services",
    "montage_mosaic_engine",
    "neid_archive",
    "neid_solar_radial_velocity_archive",
    "nexsci",
    "pan_starrs_catalog",
    "pan_starrs_catalog_api",
    "planetary_image_galleries",
    "pykoa",
    "skiff_spectral_catalog_search",
    "space_telescope_bibliographic_search",
    "spectral_classes_of_like_stars",
    "vao_datascope",
    "velocity_calculator",
    "venus_data_archive",
    "virtual_observatory_information",
    "z_mast_search",
    "ASTRO_HEASARC_Tools_Website",
    "ASTRO_HIRES_PRV_Website",
    "ASTRO_Image_Cutouts_Website",
    "ASTRO_Spitzer_Tools_Website",
    "CMR_API",
    "PDS_Annex_Data_Holdings_Website",
    "PDS_CRISM_Analysis_Toolkit_(CAT)_Website",
    "PDS_Cassini_Mission_Rhea_(Saturn_V)_Website",
    "PDS_Cassini_Mission_Saturn_Small_Satellites_Website",
    "PDS_Data_Dictionary_Search",
    "PDS_MRO_Coordinated_Observation_Website",
    "PDS_Mars_Exploration_Program_Website",
    "PDS_Mars_Orbital_Data_Explorer_Website",
    "PDS_Mission_Data_Archive_Website",
    "PDS_Missions_Archive_Page_Website",
    "PDS_NASA_Space_Science_Data_Coordinated_Archive_(NSSDCA)_Website",
    "PDS_SPICE_Self-Training_Website",
    "archived_synthetic_data",
    "astroquery_api_search_mast_queries",
    "co_plotter",
    "contributed_datasets_in_the_exoplanet_archive",
    "coordinate_calculator",
    "corot_exoplanet_archive_etss_data_sets",
    "earth_observer_publications",
    "earth_observing_dashboard",
    "exo_mast",
    "exoplanet_atmosphere_observability_table",
    "extinction_calculator",
    "f_prime",
    "goddard_institute_for_space_studies",
    "heasarc_browse_batch_interface",
    "heasarc_download_scripts",
    "high_level_science_products",
    "hubble_source_catalog_search",
    "ipac_table_validator",
    "koa_program_friendly_image_access_service",
    "lbti_archive",
    "mast",
    "mast_api_search",
    "mast_hubble_search",
    "mast_portal",
    "mast_query_casjobs",
    "mast_web_services",
    "montage_mosaic_engine",
    "neid_archive",
    "neid_solar_radial_velocity_archive",
    "nexsci",
    "pan_starrs_catalog",
    "pan_starrs_catalog_api",
    "planetary_image_galleries",
    "pykoa",
    "skiff_spectral_catalog_search",
    "space_telescope_bibliographic_search",
    "spectral_classes_of_like_stars",
    "vao_datascope",
    "velocity_calculator",
    "venus_data_archive",
    "virtual_observatory_information",
    "z_mast_search",
]


# these are all the ones changed on 2023.08.17
# update this note after running them
sources_with_new_source56_mappings = [
    "CASEI_Deployment",
    "CASEI_Instrument",
    "CASEI_Platform",
    "CEOS_API_I",
    "earth_observing_dashboard",
    "f_prime",
    "nasa_carbon_monitoring_system",
    "nasa_global_climate_change",
    "nasa_power",
    "nasa_science_missions_earth",
    "nasa_sea_level_change",
    "nasa_wavelength",
]

# these are all the ones changed on 2023.08.17
# update this note after running them
sources_with_new_selection_rule = [
    "PDS_Mars_Exploration_Program_Website",
    "goddard_institute_for_space_studies",
    "my_nasa_data",
]

# these are all the ones changed on 2023.08.17
# update this note after running them
sources_with_new_title_rule = [
    "ASTRO_Calibration_Documentation_Website",
    "ASTRO_Missions_and_Data_Website",
    "PDS_Astromaterials_Acquisition_and_Curation_Office_Website",
    "PDS_Cassini_Mission_Saturn_Small_Satellites_Website",
    "gcn_missions_instruments_and_facilities",
    "general_coordinates_network_gcn",
    "nasa_power",
]

# this is every single source on the dev branch
# we are burning the test server and rescraping all of these...
sources_to_scrape_20230929 = [
    "ARSETAppliedSciences",
    "ASTRO_API_Search_Website",
    "ASTRO_Astrophysics_Documents_Website",
    "ASTRO_Calibration_Documentation_Website",
    "ASTRO_Contributed_Datasets_Website",
    "ASTRO_Data_Hosted_on_LAMBDA_Website",
    "ASTRO_Data_Reduction_Tools_Website",
    "ASTRO_Exoplanet_Program_Documents_Website",
    "ASTRO_Finder_Chart_Website",
    "ASTRO_HEASARC_Software_Website",
    "ASTRO_HEASARC_Tools_Website",
    "ASTRO_HIRES_PRV_Website",
    "ASTRO_High-Energy_Missions_Website",
    "ASTRO_Hubble_Source_Catalog_Search_API_Website",
    "ASTRO_Image_Cutouts_Website",
    "ASTRO_James_Webb_Space_Telescope_Website",
    "ASTRO_MAST_Documentation_Website",
    "ASTRO_Missions_and_Data_Website",
    "ASTRO_Multi_Website",
    "ASTRO_NASA_Exoplanet_Archive_Documents_Website",
    "ASTRO_NAVO_HEASARC",
    "ASTRO_NED_User_Guides_Website",
    "ASTRO_Planck_Cutout_Visualization_Website",
    "ASTRO_Spitzer_Tools_Website",
    "ASTRO_TAP_Search_Website",
    "ASTRO_WISE_Image_Service_Website",
    "ASTRO_ZMAST_API_Website",
    "ASTRO_exoMAST_API_Website",
    "Algorithm_Publication_Tool",
    "Autoplot_Website",
    "CASEI",
    "CASEI_Campaign",
    "CASEI_Deployment",
    "CASEI_Instrument",
    "CASEI_Platform",
    "CCMC_Website",
    "CEOS_API_I",
    "CEOS_API_M",
    "CMR_API",
    "CODE_NASA_API",
    "Commercial_Smallsat_Data_Acquisition_CSDA_Program",
    "DataPathFinder",
    "ESSCOR_API",
    "GCIS_ARTICLE_API",
    "GCIS_BOOKS_API",
    "GCIS_JOURNAL_API",
    "GCIS_REPORTS_API",
    "GENELAB_Github_DataProcessing",
    "GENELAB_Github_SampleProcessing",
    "GENELAB_Github_Training",
    "GENELAB_METADATA_Website",
    "GENELAB_Publications_Website",
    "HAPI_API",
    "HAPI_Website",
    "Helio_Events_Knowledgebase_Website",
    "Heliophysics_Project_Data_Management_Plans",
    "Helioviewer_Documentation_Website",
    "Helioviewer_Website",
    "LSDA_Website",
    "LSDA_Website_Trial",
    "LSDA_Website_Trial2",
    "NASA_Black_Marble",
    "NASA_Climate_Change",
    "NASA_Earth_Observations",
    "NASA_Earth_Observatory",
    "NASA_Earthdata",
    "NASA_Heliophysics_Digital_Resource_Library_HDRL",
    "NASA_SPoRT",
    "NASA_Techport",
    "NASA_Worldview",
    "NAVO_HEASARC",
    "NTRS",
    "NasaEarthObservationWebsite",
    "Optical_Constants_Database",
    "PDS_API_Legacy_All",
    "PDS_All_Data_Holdings_Website",
    "PDS_Analyst_Notebook_Website",
    "PDS_Annex_Data_Holdings_Website",
    "PDS_Archive_Navigator_Website",
    "PDS_Astrogeology_Website",
    "PDS_Astromat_Astromaterials_Data_System_Website",
    "PDS_Astromaterials_Acquisition_and_Curation_Office_Website",
    "PDS_Astropedia_Lunar_and_Planetary_Cartographic_Catalog_Website",
    "PDS_Atmospheric_Escape_Chemistry_Page_Website",
    "PDS_CRISM_Analysis_Toolkit_(CAT)_Website",
    "PDS_CRISM_Spectral_Library_Website",
    "PDS_Cassini_Mission_Dione_(Saturn_IV)_Website",
    "PDS_Cassini_Mission_Enceladus_(Saturn_II)_Website",
    "PDS_Cassini_Mission_Iapetus_(Saturn_VIII)_Website",
    "PDS_Cassini_Mission_Mimas_(Saturn_I)_Website",
    "PDS_Cassini_Mission_Rhea_(Saturn_V)_Website",
    "PDS_Cassini_Mission_Saturn_Small_Satellites_Website",
    "PDS_Cassini_Mission_Tethys_(Saturn_III)_Website",
    "PDS_Cassini_Resource_Page_Website",
    "PDS_Collision_Induced_Absorption_Model_Website",
    "PDS_Current_Missions_Website",
    "PDS_DIVINER_RDR_Query_V20_Website",
    "PDS_DIVINER_RDR_Query_Website",
    "PDS_Data_Archive_Website",
    "PDS_Data_Dictionary_Search",
    "PDS_Data_Pilot_Website",
    "PDS_Data_Portal_Website",
    "PDS_Data_Volumes_Index_Website",
    "PDS_Data_Volumes_Website",
    "PDS_Dawn_Mission_to_Ceres_Website",
    "PDS_Dawn_Mission_to_Vesta_Website",
    "PDS_EPIC_Model_Website",
    "PDS_Errata_Website",
    "PDS_Generic_Kernels_Website",
    "PDS_Geosciences_Data_Holdings_Website",
    "PDS_Geosciences_Node_Spectral_Library_Website",
    "PDS_Gravity_Models_Website",
    "PDS_High-Resolution_Transmission_Molecular_Absorption_Database_(HITRAN)_Website",
    "PDS_ISIS_Astro_Website",
    "PDS_ISIS_Website",
    "PDS_Image_Atlas_Website",
    "PDS_Imaging_Software_Website",
    "PDS_Java_Mission-planning_and_Analysis_for_Remote_Sensing_(JMARS)_Website",
    "PDS_Juno_Archive_Page_Website",
    "PDS_Jupiter_Data_Archive_Website",
    "PDS_LADEE_NMS_Calibrated_Data_Search",
    "PDS_LADEE_NMS_Derived_Data_Search",
    "PDS_LADEE_UVS_Calibrated_Data_Search",
    "PDS_LOLA_RDR_Query_V20_Website",
    "PDS_LOLA_RDR_Query_Website",
    "PDS_Lunar_Atmospheres_Data_Archive_Website",
    "PDS_Lunar_Orbiter_Data_Explorer_Website",
    "PDS_MAVEN_ACC_Data_Search",
    "PDS_MAVEN_NGIMS_Data_Search",
    "PDS_MRO_Coordinated_Observation_Website",
    "PDS_Map-a-Planet_(MAP)_Website",
    "PDS_Mars_Exploration_Program_Website",
    "PDS_Mars_GCM_Website",
    "PDS_Mars_Lander_Data_Website",
    "PDS_Mars_Orbital_Data_Explorer_Website",
    "PDS_Mars_Orbiter_Data_Website",
    "PDS_Mercury_Data_Archive_Website",
    "PDS_Mercury_Orbital_Data_Explorer_Website",
    "PDS_Messenger_MASCS_UVVS_Archive_Page_Website",
    "PDS_Metadata_Injector_for_PDS_Labels_Website",
    "PDS_Mission_Data_Archive_Website",
    "PDS_Missions_Archive_Page_Website",
    "PDS_Missions_Website",
    "PDS_Models_and_Simulations_Website",
    "PDS_NASA_Science_Earths_Moon_Website",
    "PDS_NASA_Science_Solar_System_Exploration_Website",
    "PDS_NASA_Solar_System_Treks_Website",
    "PDS_NASA_Space_Science_Data_Coordinated_Archive_(NSSDCA)_Website",
    "PDS_NASAs_Eyes_Website",
    "PDS_NEAR_Shoemaker_Mission_to_433_Eros_Website",
    "PDS_Near_Earth_Asteroid_Rendezvous_(NEAR)_Data_Archive_Website",
    "PDS_Neptune_Archive_Page_Website",
    "PDS_New_Horizons_Encounter_with_Pluto_Website",
    "PDS_Niels_Bohr_Institute_Website",
    "PDS_Notebook_Website",
    "PDS_ODE_REST_Service_Website",
    "PDS_OMEGA_Analysis_Toolkit_(OAT)_Website",
    "PDS_OPUS_Website",
    "PDS_OSIRIS-REx_Mission_to_Bennu_Website",
    "PDS_Object_Access_Library_Website",
    "PDS_Odyssey_GRS_Data_Node_Website",
    "PDS_Operational_Flight_Other_Project_Kernels_Website",
    "PDS_Outer_Planets_Icy_Satellites_Archive_Page_Website",
    "PDS_PDS3_Standards_Reference_Website",
    "PDS_PDS4_Documents_Website",
    "PDS_PDS4_JParser_Website",
    "PDS_PDS4_Local_Data_Dictionary_Tool_Website",
    "PDS_PDS4_Training_Documents_Website",
    "PDS_PDS_Annex_Products_Website",
    "PDS_PDS_Atmospheres_Data_Set_Catalog_Website",
    "PDS_PDS_Documentation_Website",
    "PDS_PDS_Small_Bodies_Node_Asteroid_Dust_Subnode_Website",
    "PDS_PDS_Software_Tools_Tutorial_and_Viewers_Website",
    "PDS_PDS_Tool_Registry_Website",
    "PDS_PPI_Documents_Website",
    "PDS_PPI_Software_Website",
    "PDS_Phoebe_Saturn_IX_Website",
    "PDS_Photojournal_Website",
    "PDS_Planetary_Data_System_(PDS)_Website",
    "PDS_Planetary_Science_Tools_Website",
    "PDS_Pluto_and_Arrokoth_Data_Archive_Website",
    "PDS_Projection_on_the_Web_(POW)_Service_Website",
    "PDS_Recently_Archived_Volumes_Website",
    "PDS_Ring-Moon_Systems_Node_On-line_Tools_Website",
    "PDS_Rings_Website",
    "PDS_SBIB_3D_Website",
    "PDS_SBN_Tools_Utilities_and_Interfaces_Website",
    "PDS_SPICE-enhanced_Cosmographia_Website",
    "PDS_SPICE_Archives_Website",
    "PDS_SPICE_Programming_Lessons_Website",
    "PDS_SPICE_Self-Training_Website",
    "PDS_SPICE_Toolkit_Documentation_Website",
    "PDS_SPICE_Toolkit_Website",
    "PDS_SPICE_Tutorials_Website",
    "PDS_SPICE_Utility_and_Application_Programs_Website",
    "PDS_Saturn_Data_Archive_Website",
    "PDS_Small_Bodies_Data_Ferret_Website",
    "PDS_Small_Bodies_Image_Browser_Website",
    "PDS_Solar_System_Exploration_Research_Virtual_Institute_(SSERVI)_Website",
    "PDS_Subscription_Service_Website",
    "PDS_Subset_Tool_Website",
    "PDS_TES_Data_Node_Website",
    "PDS_Titan_Data_Archive_Website",
    "PDS_Toolkits_Website",
    "PDS_USGS_Pilot_Website",
    "PDS_Uranus_Data_Archive_Website",
    "PDS_Users_Guides_Website",
    "PDS_Venus_Archive_Page_Website",
    "PDS_Venus_Orbital_Data_Explorer_Website",
    "PDS_Virtual_Astronaut_Website",
    "PDS_Web_Chronos_Website",
    "PDS_Wind_Tunnel_Particle_Threshold_Speed_Data_Website",
    "PyHC_Website",
    "SERVIR_Global",
    "SPASE_JSON",
    "SPASE_Website",
    "SPEDAS_Website",
    "Sea_Level_Change",
    "Small_Bodies_Node",
    "Socioeconomic_Data_and_Applications_Center_SEDAC",
    "Solar_Data_Analysis_Center_SDAC",
    "Solar_Physics_Group",
    "Space_Biology_Science_Digest",
    "Space_Physics_Data_Facility",
    "Space_Place",
    "TASKBOOK_Website",
    "VEDA_Dashboard",
    "VEDA_STAC_Catalog",
    "algorithm_theoretical_basis_documents",
    "archived_synthetic_data",
    "astrogeology_analysis_ready_data",
    "astroquery_api_search_mast_queries",
    "co_plotter",
    "contributed_datasets_in_the_exoplanet_archive",
    "coordinate_calculator",
    "corot_exoplanet_archive_etss_data_sets",
    "earth_observer_publications",
    "earth_observing_dashboard",
    "earth_science_decadal_surveys",
    "emac_exoplanet_modeling_and_analysis_center",
    "eos_mission_page",
    "exo_mast",
    "exoplanet_atmosphere_observability_table",
    "exoplanet_opacities_database",
    "extinction_calculator",
    "f_prime",
    "fire_information_for_resource_management_system_firms",
    "gcn_circulars",
    "gcn_missions_instruments_and_facilities",
    "general_coordinates_network_gcn",
    "giss_datasets_and_derived_materials",
    "giss_publication_list",
    "giss_software_tools",
    "goddard_institute_for_space_studies",
    "heasarc_browse_batch_interface",
    "heasarc_download_scripts",
    "high_level_science_products",
    "hubble_source_catalog_search",
    "igwn_public_alerts_user_guide",
    "interactive_multiinstrument_database_of_solar_flares",
    "ipac_table_validator",
    "koa_program_friendly_image_access_service",
    "lbti_archive",
    "mars_target_encyclopedia_mte",
    "mast",
    "mast_api_search",
    "mast_hubble_search",
    "mast_portal",
    "mast_query_casjobs",
    "mast_web_services",
    "montage_mosaic_engine",
    "my_nasa_data",
    "naif",
    "nasa_2023_climate_strategy",
    "nasa_carbon_monitoring_system",
    "nasa_global_climate_change",
    "nasa_power",
    "nasa_science_missions_earth",
    "nasa_wavelength",
    "neid_archive",
    "neid_solar_radial_velocity_archive",
    "nexsci",
    "ntrs_api",
    "our_changing_planet_the_view_from_space_images",
    "pan_starrs_catalog",
    "pan_starrs_catalog_api",
    "pds_rings",
    "planetary_image_galleries",
    "pykoa",
    "skiff_spectral_catalog_search",
    "space_telescope_bibliographic_search",
    "spectral_classes_of_like_stars",
    "vao_datascope",
    "velocity_calculator",
    "venus_data_archive",
    "virtual_observatory_information",
    "z_mast_search",
]

# after indexing for a few days, we discovered some possible optimizations and needed
# to restart the jobs
updated_list_20231003 = [
    "heasarc_download_scripts",
    "ipac_table_validator",
    "mast_api_search",
    "montage_mosaic_engine",
    "nasa_global_climate_change",
    "neid_solar_radial_velocity_archive",
    "pan_starrs_catalog_api",
    "space_telescope_bibliographic_search",
    "virtual_observatory_information",
    "high_level_science_products",
    "koa_program_friendly_image_access_service",
    "mast_hubble_search",
    "my_nasa_data",
    "nasa_power",
    "nexsci",
    "pds_rings",
    "spectral_classes_of_like_stars",
    "z_mast_search",
    "ASTRO_Planck_Cutout_Visualization_Website",
    "ASTRO_exoMAST_API_Website",
    "CASEI_Deployment",
    "CEOS_API_M",
    "ESSCOR_API",
    "GENELAB_Github_DataProcessing",
    "HAPI_API",
    "Helioviewer_Website",
    "NASA_Climate_Change",
    "NASA_SPoRT",
    "NasaEarthObservationWebsite",
    "PDS_Annex_Data_Holdings_Website",
    "PDS_Astropedia_Lunar_and_Planetary_Cartographic_Catalog_Website",
    "PDS_Cassini_Mission_Enceladus_(Saturn_II)_Website",
    "PDS_Cassini_Mission_Tethys_(Saturn_III)_Website",
    "PDS_DIVINER_RDR_Query_Website",
    "PDS_Data_Volumes_Index_Website",
    "PDS_Errata_Website",
    "PDS_High-Resolution_Transmission_Molecular_Absorption_Database_(HITRAN)_Website",
    "PDS_Java_Mission-planning_and_Analysis_for_Remote_Sensing_(JMARS)_Website",
    "PDS_LADEE_UVS_Calibrated_Data_Search",
    "PDS_MAVEN_ACC_Data_Search",
    "PDS_Mars_GCM_Website",
    "PDS_Mercury_Orbital_Data_Explorer_Website",
    "PDS_Missions_Website",
    "PDS_NASA_Space_Science_Data_Coordinated_Archive_(NSSDCA)_Website",
    "PDS_New_Horizons_Encounter_with_Pluto_Website",
    "PDS_OPUS_Website",
    "PDS_Outer_Planets_Icy_Satellites_Archive_Page_Website",
    "PDS_PDS4_Training_Documents_Website",
    "PDS_PDS_Software_Tools_Tutorial_and_Viewers_Website",
    "PDS_Photojournal_Website",
    "PDS_Recently_Archived_Volumes_Website",
    "PDS_SPICE-enhanced_Cosmographia_Website",
    "PDS_SPICE_Toolkit_Website",
    "PDS_Small_Bodies_Image_Browser_Website",
    "PDS_Titan_Data_Archive_Website",
    "PDS_Venus_Archive_Page_Website",
    "PyHC_Website",
    "Sea_Level_Change",
    "Space_Biology_Science_Digest",
    "VEDA_STAC_Catalog",
    "co_plotter",
    "earth_observing_dashboard",
    "exoplanet_atmosphere_observability_table",
    "gcn_circulars",
    "giss_software_tools",
    "hubble_source_catalog_search",
    "lbti_archive",
    "mast_portal",
    "naif",
    "nasa_science_missions_earth",
    "ntrs_api",
    "planetary_image_galleries",
    "vao_datascope",
    "Space_Physics_Data_Facility",
    "algorithm_theoretical_basis_documents",
    "contributed_datasets_in_the_exoplanet_archive",
    "earth_science_decadal_surveys",
    "exoplanet_opacities_database",
    "gcn_missions_instruments_and_facilities",
    "goddard_institute_for_space_studies",
    "igwn_public_alerts_user_guide",
    "mars_target_encyclopedia_mte",
    "mast_query_casjobs",
    "nasa_2023_climate_strategy",
    "nasa_wavelength",
    "our_changing_planet_the_view_from_space_images",
    "pykoa",
    "velocity_calculator",
    "ASTRO_NASA_Exoplanet_Archive_Documents_Website",
    "ASTRO_TAP_Search_Website",
    "Autoplot_Website",
    "CASEI_Platform",
    "CODE_NASA_API",
    "GCIS_BOOKS_API",
    "GENELAB_Github_Training",
    "Helio_Events_Knowledgebase_Website",
    "LSDA_Website_Trial",
    "NASA_Earth_Observatory",
    "NASA_Worldview",
    "PDS_API_Legacy_All",
    "PDS_Astrogeology_Website",
    "PDS_CRISM_Analysis_Toolkit_(CAT)_Website",
    "PDS_Cassini_Mission_Mimas_(Saturn_I)_Website",
    "PDS_Collision_Induced_Absorption_Model_Website",
    "PDS_Data_Dictionary_Search",
    "PDS_Dawn_Mission_to_Ceres_Website",
    "PDS_Geosciences_Data_Holdings_Website",
    "PDS_ISIS_Website",
    "PDS_Jupiter_Data_Archive_Website",
    "PDS_LOLA_RDR_Query_Website",
    "PDS_MRO_Coordinated_Observation_Website",
    "PDS_Mars_Orbital_Data_Explorer_Website",
    "PDS_Metadata_Injector_for_PDS_Labels_Website",
    "PDS_NASA_Science_Earths_Moon_Website",
    "PDS_NEAR_Shoemaker_Mission_to_433_Eros_Website",
    "PDS_Notebook_Website",
    "PDS_Object_Access_Library_Website",
    "PDS_PDS4_Documents_Website",
    "PDS_PDS_Atmospheres_Data_Set_Catalog_Website",
    "PDS_PPI_Documents_Website",
    "PDS_Planetary_Science_Tools_Website",
    "PDS_Rings_Website",
    "PDS_SPICE_Programming_Lessons_Website",
    "PDS_SPICE_Utility_and_Application_Programs_Website",
    "PDS_Subscription_Service_Website",
    "PDS_USGS_Pilot_Website",
    "PDS_Virtual_Astronaut_Website",
    "SPASE_JSON",
    "Socioeconomic_Data_and_Applications_Center_SEDAC",
    "Space_Place",
    "archived_synthetic_data",
    "coordinate_calculator",
    "emac_exoplanet_modeling_and_analysis_center",
    "extinction_calculator",
    "general_coordinates_network_gcn",
    "heasarc_browse_batch_interface",
    "interactive_multiinstrument_database_of_solar_flares",
    "mast",
    "mast_web_services",
    "nasa_carbon_monitoring_system",
    "neid_archive",
    "pan_starrs_catalog",
    "skiff_spectral_catalog_search",
    "venus_data_archive",
    # long jobs...
    "giss_datasets_and_derived_materials",
    "ASTRO_Missions_and_Data_Website",
    "Small_Bodies_Node",
    "ASTRO_Image_Cutouts_Website",
]

update_base_href = [
    "SERVIR_Global",
    "Sea_Level_Change",
    "Solar_Physics_Group",
    "Space_Physics_Data_Facility",
    "astroquery_api_search_mast_queries",
    "contributed_datasets_in_the_exoplanet_archive",
    "corot_exoplanet_archive_etss_data_sets",
    "exo_mast",
    "exoplanet_atmosphere_observability_table",
    "extinction_calculator",
    "gcn_circulars",
    "interactive_multiinstrument_database_of_solar_flares",
    "mast",
    "mast_api_search",
    "mast_portal",
    "neid_archive",
    "our_changing_planet_the_view_from_space_images",
    "pan_starrs_catalog",
    "pan_starrs_catalog_api",
    "space_telescope_bibliographic_search",
    "spectral_classes_of_like_stars",
    "vao_datascope",
    "velocity_calculator",
    "z_mast_search",
]

deploy_to_prod_20231027 = [
    "interactive_multiinstrument_database_of_solar_flares",
    "SPEDAS_Website",
    "Helioviewer_Documentation_Website",
    "GENELAB_Publications_Website",
    "contributed_datasets_in_the_exoplanet_archive",
    "corot_exoplanet_archive_etss_data_sets",
    "exo_mast",
    "exoplanet_atmosphere_observability_table",
    "exoplanet_opacities_database",
    "mast",
]

sources_to_delete_20231031 = [
    "PDS_Odyssey_GRS_Data_Node_Website",
    "PDS_Map-a-Planet_(MAP)_Website",
    "PDS_Projection_on_the_Web_(POW)_Service_Website",
    "PDS_LADEE_NMS_Derived_Data_Search",
    "PDS_LADEE_NMS_Calibrated_Data_Search",
    "PDS_Wind_Tunnel_Particle_Threshold_Speed_Data_Website",
    "exofop_k2_campaign_9",
    "GENELAB_METADATA_Website",
    "pds_geosciences_node_community",
    "2mass_batch_image_service",
    "2mass_api_search",
    "2mass_interactive_image_service",
    "2mass_image_inventory_search",
    "image_and_spectrum_server_atlas",
    "atlas_api_search",
    "background_model",
    "galactic_dust_reddening_and_extinction",
    "ASTRO_Finder_Chart_Website",
    "irsa_api",
    "herschel_data_search",
    "hires",
    "wise_neowise_coadder",
    "image_validation",
    "object_coordinate_lookup",
    "most",
    "scanpi",
    "swas_spectrum_server",
    "swas_api_search",
    "planck_data_tools",
    "irsa_votable_access_protocol",
    "vo_simple_cone_search",
    "ssa_queries",
    "irsa_idl_tools",
    "PDS_Web_Chronos_Website",
    "PDS_Subset_Tool_Website",
    "PDS_SPICE-enhanced_Cosmographia_Website",
    "PDS_SPICE_Archives_Website",
    "PDS_Operational_Flight_Other_Project_Kernels_Website",
    "PDS_SPICE_Toolkit_Documentation_Website",
    "PDS_SPICE_Programming_Lessons_Website",
    "PDS_SPICE_Toolkit_Website",
    "PDS_SPICE_Tutorials_Website",
    "PDS_SPICE_Utility_and_Application_Programs_Website",
    "PDS_Generic_Kernels_Website",
    "PDS_Niels_Bohr_Institute_Website",
    "PDS_PDS_Atmospheres_Data_Set_Catalog_Website",
    "PDS_LADEE_UVS_Calibrated_Data_Search",
    "PDS_Recently_Archived_Volumes_Website",
    "PDS_Object_Access_Library_Website",
    "ftp_access",
    "index",
    "PDS_Data_Archive_Website",
    "PDS_All_Data_Holdings_Website",
    "PDS_PDS_Software_Tools_Tutorial_and_Viewers_Website",
    "PDS_Data_Volumes_Index_Website",
    "PDS_PPI_Documents_Website",
    "PDS_Missions_Website",
    "PDS_Errata_Website",
    "PDS_Data_Volumes_Website",
    "PDS_Models_and_Simulations_Website",
    "PDS_Rings_Website",
    "viewmaster_data_archives_calibrated",
    "viewmaster_data_archives_diagrams",
    "viewmaster_data_archives_previews",
    "viewmaster_data_archives_volumes",
    "viewmaster_data_calibrated",
    "viewmaster_data_diagrams",
    "viewmaster_documents",
    "viewmaster_data_previews",
    "viewmaster_data_volumes",
    "small_bodies_node_data_by_type_of_observation",
    "PDS_Mission_Data_Archive_Website",
    "small_bodies_node_data_by_target_type",
    "data_set_status",
    "PDS_Subscription_Service_Website",
    "PDS_USGS_Pilot_Website",
    "PDS_OSIRIS-REx_Mission_to_Bennu_Website",
    "PDS_Dawn_Mission_to_Ceres_Website",
    "PDS_Cassini_Mission_Dione_(Saturn_IV)_Website",
    "PDS_Cassini_Mission_Enceladus_(Saturn_II)_Website",
    "PDS_NEAR_Shoemaker_Mission_to_433_Eros_Website",
    "PDS_Cassini_Mission_Iapetus_(Saturn_VIII)_Website",
    "PDS_Cassini_Mission_Mimas_(Saturn_I)_Website",
    "PDS_Phoebe_Saturn_IX_Website",
    "PDS_New_Horizons_Encounter_with_Pluto_Website",
    "PDS_Cassini_Mission_Rhea_(Saturn_V)_Website",
    "PDS_Cassini_Mission_Tethys_(Saturn_III)_Website",
    "PDS_Dawn_Mission_to_Vesta_Website",
    "PDS_SBIB_3D_Website",
    "PDS_Cassini_Mission_Saturn_Small_Satellites_Website",
    "PDS_Small_Bodies_Data_Ferret_Website",
    "PDS_Astromat_Astromaterials_Data_System_Website",
    "PDS_ISIS_Website",
    "navo_registry",
    "PDS_Planetary_Data_System_(PDS)_Website",
    "ASTRO_Multi_Website",
    "LSDA_Website_Trial",
    "LSDA_Website_Trial2",
    "PDS_PDS_Documentation_Website",
    "PDS_Data_Portal_Website",
    "PDS_Image_Atlas_Website",
    "PDS_Imaging_Software_Website",
    "PDS_Users_Guides_Website",
    "GENELAB_Publications_Website",
]


sources_to_index_20240618 = [
    "Mission_Independent_Data_Layer",
    "koa_keck_observatory_archive",
    "interstellar_mapping_and_acceleration_probe",
    "explorers_and_heliophysics_projects_division",
    "interstellar_boundary_explorer_ibex",
    "polarimeter_to_unify_the_corona_and_heliosphere",
    "helioswarm",
    "voyager",
    "earth_science_office_at_msfc",
    "earth_system_science_pathfinder",
    "cloudsat",
    "carve_carbon_in_arctic_reservoirs_vulnerability_experiment",
    "a_train_the_afternoon_constellation",
    "cygnss_cyclone_global_navigation_satellite_system",
    "dcotss_dynamics_and_chemistry_of_the_summer_stratosphere",
    "delta_x",
    "center_for_climate_sciences",
]

sources_to_index_20240717 = [
    "nasa_ames_intelligent_systems_division_data",
    "chandra_x_ray_observatory",
    "hi_c_at_msfc",
    "tandem_reconnection_and_cusp_electrodynamics_reconnaissance_satellites",
    "sungrazer_project",
    "solar_system_dynamics",
    "lowell_minor_planet_services",
    "explorer_1",
    "earth_sciences_at_gsfc",
    "earth_science_at_jpl",
    "ecostress",
    "seabass",
    "ecostress_spectral_library",
    "unite_unistellar_network_investigating_tess_exoplanets",
    "satellite_situation_center_sscweb_system_and_services",
    "the_astrophysics_astrochemistry_lab",
    "hubble_space_telescope",
    "galprop",
    "chandra_x_ray_center_cxc",
]

sources_to_index_20240730 = [
    "gcn_circulars",
    "gamma_ray_astrophysics_at_the_nsstc",
    "asteroid_lightcurve_photometry_database",
    "orbital_data_explorer",
    "asdc_misr",
    "archived_gcn",
    "ghrc_global_hydrometeorology_resource_center",
    "NASA_Earth_Observatory",
    "aurorasaurus_reporting_auroras_from_the_ground_up",
    "hinode_at_msfc",
    "osiris_rex_asteroid_sample_return_mission",
    "grace_and_grace_fo_groundwater_and_soil_moisture_conditions",
    "sun_climate_powered_by_solar_irradiance",
    "icesat_2_ice_cloud_and_land_elevation_satellite_2",
    "spruce_spruce_and_peatland_responses_under_changing_environments",
    "tess_transitioning_exoplanet_survey_satellite",
    "iasc_international_astronomical_search_collaboration",
    "debit_dynamic_eclipse_broadcast_initiative",
    "astropix",
    "Space_Physics_Data_Facility",
    "PDS_Photojournal_Website",
]

sources_with_neural_and_plugin = [
    "Geosciences_Node",
    "Helioviewer_Documentation_Website",
    "International_Heliophysics_Data_Environment_Alliance_Overview_IHDEA",
    "act_america_atmospheric_carbon_and_transport_america",
    "activate_aerosol_cloud_meteorology_interactions_over_the_western_atlantic_experiment",
    "advanced_composition_explorer",
    "airmoss_airborne_microwave_observatory_of_subcanopy_and_subsurface_at_jpl",
    "aria_advanced_rapid_imaging_and_analysis",
    "atmospheric_imaging_assembly",
    "explorer_program_acquisition",
    "fast_plasma_investigation",
    "fermi_at_gsfc",
    "hawc_observatory",
    "hinode_solar_b",
    "incus_investigation_of_convective_updrafts",
    "interactive_nasa_space_physics_ionosphere_radio_experiments_inspire",
    "iris_interface_region_imaging_spectrograph",
    "jwst_user_documentation",
    "ldas_land_data_assimilatin_system",
    "lisa_consortium",
    "mdscc_deep_space_network",
    "microobservatory_robotic_telescope_network",
    "naif",
    "nasa_applied_sciences",
    "nasa_arcgis_online",
    "nasa_infrared_telescope_facility_irtf",
    "nasa_sounding_rocket_program",
    "parker_solar_probe",
    "pds_cartography_and_imaging_sciences_node",
    "pds_website",
    "physics_of_the_cosmos",
    "ppi_node",
    "pps_precipitation_processing_system",
    "radio_jove",
    "rhessi_homepage",
    "sampex_data_center",
    "sdo_solar_dynamics_observatory",
    "solar_terrestrial_probes_program",
    "starchild_a_learning_center_for_young_astronomers",
    "stereo_at_gsfc",
    "stereo_cor1",
    "the_new_great_observatories",
    "treasure_map",
    "vector_electric_field_instrument",
    "virbo",
    "virtual_wave_observatory",
]

sources_to_index_test_grid = [
    "a_train_the_afternoon_constellation",
    "act_america_atmospheric_carbon_and_transport_america",
    "activate_aerosol_cloud_meteorology_interactions_over_the_western_atlantic_experiment",
    "advanced_composition_explorer",
    "Advancing_the_science_of_heliophysics",
    "airmoss_airborne_microwave_observatory_of_subcanopy_and_subsurface_at_jpl",
    "archived_gcn",
    "aria_advanced_rapid_imaging_and_analysis",
    "asdc_misr",
    "asteroid_lightcurve_photometry_database",
    "astronomy_picture_of_the_day",
    "astrophysics_source_code_library",
    "astropix",
    "astropy",
    "atmospheric_imaging_assembly",
    "aurorasaurus_reporting_auroras_from_the_ground_up",
    "carve_carbon_in_arctic_reservoirs_vulnerability_experiment",
    "cdaw_data_center",
    "center_for_climate_sciences",
    "chandra_x_ray_center_cxc",
    "chandra_x_ray_observatory",
    "cii_hosted_payload_opportunity_online_database",
    "cloudsat",
    "cosmic_data_stories",
    "cygnss_cyclone_global_navigation_satellite_system",
    "dcotss_dynamics_and_chemistry_of_the_summer_stratosphere",
    "debit_dynamic_eclipse_broadcast_initiative",
    "delta_x",
    "dscovr_epic_earth_polychromatic_imaging_camera",
    "earth_science_at_jpl",
    "earth_science_office_at_msfc",
    "earth_system_science_pathfinder",
    "ecostress",
    "ecostress_spectral_library",
    "explorer_1",
    "explorer_program_acquisition",
    "explorers_and_heliophysics_projects_division",
    "fast_plasma_investigation",
    "fermi_at_gsfc",
    "galprop",
    "gamma_ray_astrophysics_at_the_nsstc",
    "gamma_ray_data_tools_core_package",
    "gamma_ray_data_tools_github",
    "Geosciences_Node",
    "ghrc_global_hydrometeorology_resource_center",
    "global_sulfur_dioxide_monitoring",
    "gmao_fluid",
    "grace_and_grace_fo_groundwater_and_soil_moisture_conditions",
    "hawc_observatory",
    "HelioAnalytics",
    "helionauts",
    "heliophysics_digital_observatory",
    "heliophysics_system_observatory_connect",
    "helioswarm",
    "Helioviewer_Documentation_Website",
    "hi_c_at_msfc",
    "hinode_at_msfc",
    "hinode_solar_b",
    "hpde_github",
    "hubble_space_telescope",
    "icesat_2_ice_cloud_and_land_elevation_satellite_2",
    "incus_investigation_of_convective_updrafts",
    "interactive_nasa_space_physics_ionosphere_radio_experiments_inspire",
    "International_Heliophysics_Data_Environment_Alliance_Overview_IHDEA",
    "interstellar_boundary_explorer_ibex",
    "interstellar_mapping_and_acceleration_probe",
    "iris_interface_region_imaging_spectrograph",
    "JWST_User_Documentation",
    "koa_keck_observatory_archive",
    "land_processes_distributed_active_archive_center",
    "ldas_land_data_assimilatin_system",
    "lisa_consortium",
    "Living_with_a_Star",
    "lowell_minor_planet_services",
    "magnetospheric_multiscale_satellites",
    "mdscc_deep_space_network",
    "microobservatory_robotic_telescope_network",
    "Mission_Independent_Data_Layer",
    "naif",
    "nasa_ames_intelligent_systems_division_data",
    "nasa_applied_sciences",
    "nasa_arcgis_online",
    "NASA_Earth_Observatory",
    "nasa_infrared_telescope_facility_irtf",
    "nasa_sounding_rocket_program",
    "nasa_visible_earth",
    "national_space_weather_program",
    "neil_gehrel_s_swift_observatory",
    "orbital_data_explorer",
    "osiris_rex_asteroid_sample_return_mission",
    "parker_solar_probe",
    "pds_atmospheres",
    "pds_cartography_and_imaging_sciences_node",
    "pds_nasa_solar_system_treks_website",
    "PDS_Photojournal_Website",
    "pds_rings",
    "pds_website",
    "physics_of_the_cosmos",
    "polarimeter_to_unify_the_corona_and_heliosphere",
    "ppi_node",
    "pps_precipitation_processing_system",
    "radio_jove",
    "rhessi_homepage",
    "sampex_data_center",
    "satellite_situation_center_sscweb_system_and_services",
    "sdo_solar_dynamics_observatory",
    "seabass",
    "sep_instrument_suite",
    "Small_Bodies_Node",
    "solar_and_heliospheric_observatory_soho",
    "Solar_Physics_Group",
    "solar_system_dynamics",
    "solar_terrestrial_probes_program",
    "spruce_spruce_and_peatland_responses_under_changing_environments",
    "starchild_a_learning_center_for_young_astronomers",
    "stereo_at_gsfc",
    "stereo_cor1",
    "sun_climate_powered_by_solar_irradiance",
    "sungrazer_project",
    "tandem_reconnection_and_cusp_electrodynamics_reconnaissance_satellites",
    "TASKBOOK_Website",
    "tess_transitioning_exoplanet_survey_satellite",
    "the_astrophysics_astrochemistry_lab",
    "the_new_great_observatories",
    "treasure_map",
    "unite_unistellar_network_investigating_tess_exoplanets",
    "Van_Allen_Probes",
    "vector_electric_field_instrument",
    "virtual_solar_observatory",
    "virtual_wave_observatory",
    "voyager",
    "Voyager_Cosmic_Ray_Subsystem",
    "WIND_Spacecraft",
]

missing_indexers = [
    "Advancing_the_science_of_heliophysics",
    "HelioAnalytics",
    "JWST_User_Documentation",
    "Living_with_a_Star",
    "pds_nasa_solar_system_treks_website",
    "solar_and_heliospheric_observatory_soho",
]

sources_to_index_test_grid_20240809 = [s for s in sources_to_index_test_grid if s not in missing_indexers]
