name: Django Test Suite on PR

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**/*.md'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged
        ports:
          - 5432:5432

    steps:
      - name: Check out merged code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build the Docker environment
        run: docker-compose -f local.yml build

      - name: Run test suite
        env:
          DJANGO_ENV: test
        run: docker-compose -f local.yml run --rm django bash ./init.sh

      - name: Generate Coverage Report
        env:
          DJANGO_ENV: test
        run: docker-compose -f local.yml run --rm django bash -c "coverage report"

      - name: Cleanup
        run: docker-compose -f local.yml down --volumes
